var path = require('path');

var version = '1.3'; // the version from the git repo branch

module.exports = function(grunt) {
  'use strict';

  grunt.loadNpmTasks('grunt-svgmin');
  grunt.loadNpmTasks('grunt-webfont');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-grunticon');
  grunt.loadNpmTasks('grunt-includes');

  grunt.initConfig({
    // 1. We want to minify the source SVG icons
    // TODO:
    // - add compression for common source folders
    // - remove generic, functional, social as those are archived and won't be changed
    svgmin: {
      chemistry: {
        files: [{
          expand: true,
          cwd: 'source/chemistry',
          src: ['*.svg'],
          dest: 'source/chemistry'
        }]
      },
      conceptual: {
        files: [{
          expand: true,
          cwd: 'source/conceptual',
          src: ['*.svg'],
          dest: 'source/conceptual'
        }]
      },
      fileformats: {
        files: [{
          expand: true,
          cwd: 'source/fileformats',
          src: ['*.svg'],
          dest: 'source/fileformats'
        }]
      },
      functional: {
        files: [{
          expand: true,
          cwd: 'source/functional',
          src: ['*.svg'],
          dest: 'source/functional'
        }]
      },
      generic: {
        files: [{
          expand: true,
          cwd: 'source/generic',
          src: ['*.svg'],
          dest: 'source/generic'
        }]
      },
      social: {
        files: [{
          expand: true,
          cwd: 'source/social',
          src: ['*.svg'],
          dest: 'source/social'
        }]
      },
      species: {
        files: [{
          expand: true,
          cwd: 'source/species',
          src: ['*.svg'],
          dest: 'source/species'
        }]
      }
    },
    // 2. Build the icon fonts
    //    and we want to specify the letter codes
    webfont: {
      'EBI-Species': {
        src: 'source/species/*.svg',
        dest: 'EBI-Species/fonts',
        // destCss: 'EBI-Species',
        options: {
          version: version,
          font: 'EBI-Species',
          fontFamilyName: 'EBI-Species',
          fontFilename: 'EBI-Species',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-species',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'ferret': 0x0021,
            'bee': 0x0024,
            'brachypodium': 0x0025,
            'tick': 0x0026,
            'bat': 0x0028,
            'tomatoes': 0x0029,
            'orangutan': 0x002a,
            'amoeba': 0x0030,
            'mosquito': 0x0031,
            'diatom': 0x0032,
            'kangaroo-rat': 0x0033,
            'louse': 0x0034,
            'barley': 0x0035,
            'rice': 0x0036,
            'anolis': 0x0037,
            'papio': 0x0038,
            'monodelphis': 0x0039,
            'plasmodium': 0x0040,
            'cat': 0x0041,
            'brassica': 0x0042,
            'cow': 0x0043,
            'dolphin': 0x0044,
            'pufferfish': 0x0045,
            'fly': 0x0046,
            'gorilla': 0x0047,
            'human': 0x0048,
            'squirrel': 0x0049,
            'ecoli': 0x004c,
            'mouse': 0x004d,
            'mouse-lemur': 0x004e,
            'grapes': 0x004f,
            'plant': 0x0050,
            'shrew': 0x0051,
            'rat': 0x0052,
            'spider': 0x0053,
            'platypus': 0x0055,
            'c-elegans': 0x0057,
            'yeast': 0x0059,
            'zebrafish': 0x005a,
            'glycinemax': 0x005e,
            'alpaca': 0x0061,
            'bug': 0x0062,
            'corn': 0x0063,
            'dog': 0x0064,
            'elephant': 0x0065,
            'frog': 0x0066,
            'guinea-pig': 0x0067,
            'horse': 0x0068,
            'chimpanzee': 0x0069,
            'chicken': 0x006b,
            'armadillo': 0x006c,
            'finch': 0x006e,
            'hedgehog': 0x006f,
            'pig': 0x0070,
            'monkey': 0x0072,
            'scorpion': 0x0073,
            'rabbit': 0x0074,
            'fungus': 0x0075,
            'virus': 0x0076,
            'wallaby': 0x0077,
            'sheep': 0x0078,
            'aspergillus': 0x00a3,
            'goat': 0x006d,
            'snail': 0x0027,
            'ray': 0x002b
          }
        }
      },
      'EBI-SocialMedia': {
        src: 'source/social/*.svg',
        dest: 'EBI-SocialMedia/fonts',
        // destCss: 'EBI-SocialMedia',
        options: {
          version: version,
          font: 'EBI-SocialMedia',
          fontFamilyName: 'EBI-SocialMedia',
          fontFilename: 'EBI-SocialMedia',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-socialmedia',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'android': 0x0061,
            'apple': 0x0041,
            'blogger': 0x0042,
            'facebook': 0x0046,
            'flickr': 0x0066,
            'github': 0x0067,
            'googleplus': 0x0047,
            'linkedin': 0x004c,
            'linux': 0x0058,
            'orcid': 0x004f,
            'rss': 0x0052,
            'skype': 0x0073,
            'slideshare': 0x0053,
            'twitter': 0x0054,
            'vimeo': 0x0056,
            'weibo': 0x0057,
            'windows': 0x0077,
            'wordpress': 0x0050,
            'youtube': 0x0059
          }
        }
      },
      'EBI-Generic': {
        src: 'source/generic/*.svg',
        dest: 'EBI-Generic/fonts',
        // destCss: 'EBI-Generic',
        options: {
          version: version,
          font: 'EBI-Generic',
          fontFamilyName: 'EBI-Generic',
          fontFilename: 'EBI-Generic',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-generic',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'accommodation': 0x0061,
            'alert': 0x006c,
            'alumni': 0x0041,
            'announcement': 0x0055,
            'basket': 0x0062,
            'beta': 0x003e,
            'bike': 0x0033,
            'biotech': 0x0042,
            'bus': 0x0031,
            'calendar': 0x0072,
            'camera': 0x0021,
            'car': 0x0032,
            'careers': 0x0063,
            'classification': 0x0065,
            'clock': 0x007b,
            'contact': 0x0043,
            'crosslink': 0x0064,
            'database': 0x0044,
            'discuss': 0x005c,
            'documentation': 0x003b,
            'drug': 0x0075,
            'elixir': 0x0025,
            'email': 0x0045,
            'embl': 0x0026,
            'external-link': 0x0078,
            'external-systems': 0x0079,
            'face-to-face': 0x0066,
            'find-us': 0x005d,
            'funding': 0x0046,
            'graph': 0x0067,
            'group': 0x007d,
            'gtls': 0x0047,
            'health': 0x0068,
            'help': 0x003f,
            'home': 0x0048,
            'industry': 0x0049,
            'info': 0x0069,
            'link': 0x004c,
            'location': 0x005b,
            'lovedata': 0x006f,
            'mailing-list': 0x006d,
            'math': 0x0076,
            'meet-us': 0x004d,
            'mobile-device': 0x002f,
            'new': 0x003c,
            'newcomers': 0x006e,
            'news': 0x004e,
            'nutraceuticals': 0x0022,
            'open-day': 0x004f,
            'piechart': 0x0070,
            'plane': 0x0034,
            'publication': 0x0050,
            'research': 0x0029,
            'resource': 0x0052,
            'reviewed-data': 0x0071,
            'services': 0x0028,
            'steps': 0x0023,
            'support': 0x0073,
            'systems': 0x0053,
            'terms': 0x0027,
            'test': 0x0030,
            'text-mining': 0x0058,
            'toolkit': 0x003a,
            'train': 0x0037,
            'training': 0x0054,
            'tutorial': 0x0074,
            'unreviewed-data': 0x0051,
            'video': 0x0056,
            'walk': 0x0036
          }
        }
      },
      'EBI-Functional': {
        src: 'source/functional/*.svg',
        dest: 'EBI-Functional/fonts',
        // destCss: 'EBI-Functional',
        options: {
          version: version,
          font: 'EBI-Functional',
          fontFamilyName: 'EBI-Functional',
          fontFilename: 'EBI-Functional',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-functional',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'add': 0x002b,
            'add-job': 0x0029,
            'add-user': 0x0037,
            'align': 0x0069,
            'analyse': 0x0041,
            'analyse-percent_0': 0x0042,
            'analyse-percent_40': 0x0043,
            'analyse-percent_100': 0x0045,
            'analyse-graph': 0x007a,
            'approve': 0x002f,
            'approved-job': 0x0028,
            'attach': 0x0061,
            'browse': 0x0062,
            'close': 0x0078,
            'collapse': 0x0077,
            'collapse-closed': 0x0039,
            'collapse-open': 0x0038,
            'compare': 0x004f,
            'crop': 0x005c,
            'cut': 0x0063,
            'database-submit': 0x0044,
            'delete': 0x0064,
            'download': 0x003d,
            'down-page': 0x2b07,
            'edit': 0x0065,
            'edit-user': 0x0035,
            'expand': 0x0075,
            'filter': 0x0066,
            'first-page': 0x005b,
            'fullscreen': 0x0046,
            'hierarchy': 0x0068,
            'last-page': 0x005d,
            'like': 0x006b,
            'lock': 0x004c,
            'login': 0x006c,
            'mapping': 0x0030,
            'menu': 0x004d,
            'move': 0x006d,
            'next-page': 0x003e,
            'play': 0x0076,
            'previous-page': 0x003c,
            'print': 0x0050,
            'redo': 0x007d,
            'refresh': 0x0052,
            'remove': 0x002d,
            'remove-user': 0x0036,
            'save': 0x0053,
            'scaleable': 0x0059,
            'search': 0x0031,
            'search-document': 0x006a,
            'send': 0x006e,
            'settings': 0x0073,
            'share': 0x0072,
            'stop': 0x006f,
            'submit': 0x005f,
            'target': 0x0054,
            'tool': 0x0074,
            'unassigned-job': 0x002a,
            'undo': 0x007b,
            'unlock': 0x0055,
            'up-page': 0x2b06,
            'view': 0x0034,
            'zoom-in': 0x0033,
            'zoom-out': 0x0032
          }
        }
      },
      'EBI-Conceptual': {
        src: 'source/conceptual/*.svg',
        dest: 'EBI-Conceptual/fonts',
        // destCss: 'EBI-Conceptual',
        options: {
          version: version,
          font: 'EBI-Conceptual',
          fontFamilyName: 'EBI-Conceptual',
          fontFilename: 'EBI-Conceptual',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-conceptual',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'chemical': 0x0062,
            'cross-domain': 0x0063,
            'dna': 0x0064,
            'expression': 0x0067,
            'literature': 0x006c,
            'ontology': 0x006f,
            'proteins': 0x0050,
            'structures': 0x0073,
            'systems': 0x0079
          }
        }
      },
      'EBI-FileFormats': {
        src: 'source/fileformats/*.svg',
        dest: 'EBI-FileFormats/fonts',
        // destCss: 'EBI-FileFormats',
        options: {
          version: version,
          font: 'EBI-FileFormats',
          fontFamilyName: 'EBI-FileFormats',
          fontFilename: 'EBI-FileFormats',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-fileformats',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'ZIP': 0x005a,
            'Postscript': 0x0033,
            'XML': 0x0078,
            'DOC': 0x0064,
            'TXT': 0x0074,
            'TSV': 0x0076,
            'SDF': 0x0073,
            'RXN': 0x0058,
            'RDF_XML': 0x0044,
            'RD': 0x0072,
            'PSI-MI_XML': 0x0031,
            'PSI-MI_TAB': 0x0032,
            'PDF': 0x0070,
            'OWL': 0x006f,
            'OBO': 0x004f,
            'MDL': 0x004d,
            'JSON': 0x004a,
            'IMG': 0x0049,
            'GFF': 0x0047,
            'FLAT': 0x0046,
            'FASTQ': 0x0066,
            'FASTA': 0x0061,
            'CSV': 0x0063,
            'CRAM': 0x0052,
            'CML': 0x0043,
            'BAM': 0x0042,
            'AGP': 0x0041
          }
        }
      },
      'EBI-Chemistry': {
        src: 'source/chemistry/*.svg',
        dest: 'EBI-Chemistry/fonts',
        // destCss: 'EBI-Chemistry',
        options: {
          version: version,
          font: 'EBI-Chemistry',
          fontFamilyName: 'EBI-Chemistry',
          fontFilename: 'EBI-Chemistry',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-chemistry',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'direction_unknown': 0x0055,
            'direction_right': 0x0072,
            'direction_left': 0x006c,
            'direction_reversible': 0x0052
          }
        }
      },
      'EBI-Common': {
        src: 'source/common/**/*.svg',
        dest: 'EBI-Common/fonts',
        // destCss: 'EBI-SocialMedia',
        options: {
          version: version,
          font: 'EBI-Common',
          fontFamilyName: 'EBI-Common',
          fontFilename: 'EBI-Common',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-common',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            // Old social icons
            'android': 0x1F916,
            'apple': 0x1F34F,
            'blogger': 0x1F524,
            'facebook': 0x1F4D8,
            'flickr': 0x1F4F7,
            'github': 0x1F9EE,
            'googleplus': 0x1F4D5,
            'linkedin': 0x1F4C7,
            'linux': 0x1F193,
            'orcid': 0x1F4C3,
            'rss': 0x1F4F0,
            'skype': 0x1F4F3,
            'slideshare': 0x1F3A4,
            'twitter': 0x1F426,
            'vimeo': 0x1F39E,
            'weibo': 0x1F472,
            'windows': 0x1F3E2,
            'wordpress': 0x1F4D3,
            'youtube': 0x1F4FD,
            // old functional icons
            'add': 0x002b,
            'add-job': 0x0029,
            'add-user': 0x0037,
            'align': 0x0069,
            'analyse': 0x0041,
            'analyse-percent_0': 0x0042,
            'analyse-percent_40': 0x0043,
            'analyse-percent_100': 0x0045,
            'analyse-graph': 0x007a,
            'approve': 0x002f,
            'approved-job': 0x0028,
            'attach': 0x0061,
            'browse': 0x0062,
            'close': 0x0078,
            'collapse': 0x0077,
            'collapse-closed': 0x0039,
            'collapse-open': 0x0038,
            'compare': 0x004f,
            'crop': 0x005c,
            'cut': 0x0063,
            'database-submit': 0x0044,
            'delete': 0x0064,
            'download': 0x003d,
            'down-page': 0x2b07,
            'edit': 0x0065,
            'edit-user': 0x0035,
            'expand': 0x0075,
            'filter': 0x0066,
            'first-page': 0x005b,
            'fullscreen': 0x0046,
            'hierarchy': 0x0068,
            'last-page': 0x005d,
            'like': 0x006b,
            'lock': 0x004c,
            'login': 0x006c,
            'mapping': 0x0030,
            'menu': 0x004d,
            'move': 0x006d,
            'next-page': 0x003e,
            'play': 0x0076,
            'previous-page': 0x003c,
            'print': 0x0050,
            'redo': 0x007d,
            'refresh': 0x0052,
            'remove': 0x002d,
            'remove-user': 0x0036,
            'save': 0x0053,
            'scaleable': 0x0059,
            'search': 0x0031,
            'search-document': 0x006a,
            'send': 0x006e,
            'settings': 0x0073,
            'share': 0x0072,
            'stop': 0x006f,
            'submit': 0x005f,
            'target': 0x0054,
            'tool': 0x0074,
            'unassigned-job': 0x002a,
            'undo': 0x007b,
            'unlock': 0x0055,
            'up-page': 0x2b06,
            'view': 0x0034,
            'zoom-in': 0x0033,
            'zoom-out': 0x0032,
            // Old generic icons
            'accommodation': 0x1F3E8,
            'alert': 0x1F6A8,
            'alumni': 0x1F393,
            'announcement': 0x1F4DC,
            'basket': 0x1F6D2,
            'beta': 0x1F606,
            'bike': 0x1F6B4,
            'biotech': 0x1F48A,
            'bus': 0x1F68C,
            'calendar': 0x1F4C5,
            'camera': 0x0021,
            'car': 0x1F697,
            'careers': 0x1F3D9,
            'classification': 0x1F5C2,
            'clock': 0x23F0,
            'contact': 0x260E,
            'crosslink': 0x1F4CD,
            'database': 0x1F4BF,
            'discuss': 0x1F4AC,
            'documentation': 0x003b,
            'drug': 0x2695,
            'elixir': 0x0025,
            'email': 0x1F4E7,
            'embl': 0x0026,
            'external-link': 0x1F6AA,
            'external-systems': 0x0079,
            'face-to-face': 0x1F46F,
            'find-us': 0x1F9ED,
            'funding': 0x1F4B6,
            'graph': 0x0067,
            'group': 0x1F46A,
            'gtls': 0x0047,
            'health': 0x1F912,
            'help': 0x003f,
            'home': 0x0048,
            'industry': 0x1F3ED,
            'info': 0x2139,
            'link': 0x1F517,
            'location': 0x1F5FA,
            'lovedata': 0x1F91F,
            'mailing-list': 0x1F3E4,
            'math': 0x1F523,
            'meet-us': 0x1F46C,
            'mobile-device': 0x1F4F1,
            'new': 0x1F195,
            'newcomers': 0x1F68D,
            'news': 0x004e,
            'nutraceuticals': 0x0022,
            'open-day': 0x1F44B,
            'piechart': 0x0070,
            'plane': 0x2708,
            'publication': 0x1F4DA,
            'research': 0x1F52C,
            'resource': 0x1F340,
            'reviewed-data': 0x0071,
            'services': 0x1F527,
            'steps': 0x0023,
            'support': 0x1F9B8,
            'systems': 0x1F50C,
            'terms': 0x0027,
            'test': 0x1F97D,
            'text-mining': 0x0058,
            'toolkit': 0x003a,
            'train': 0x1F682,
            'training': 0x1F3EB,
            'tutorial': 0x1F4DD,
            'unreviewed-data': 0x0051,
            'video': 0x0056,
            'walk': 0x1F6B6,
            // Font-Awesome
            // Where possible these use the original Font Awesome key mappings
            'address-book': 0x02b9,
            'address-card': 0x02bb,
            'adjust': 0x0042,
            // 'align-center': 0x0037,
            // 'align-justify': 0x0039,
            // 'align-left': 0x0036,
            // 'align-right': 0x0038,
            'ambulance': 0x00f9,
            'american-sign-language-interpreting': 0x02a3,
            'anchor': 0x013d,
            'angle-double-down': 0x0103,
            'angle-double-left': 0x0100,
            'angle-double-right': 0x0101,
            'angle-double-up': 0x0102,
            'angle-down': 0x0107,
            'angle-left': 0x0104,
            'angle-right': 0x0105,
            'angle-up': 0x0106,
            'archive': 0x0187,
            'arrow-alt-circle-down': 0x0358,
            'arrow-alt-circle-left': 0x0359,
            'arrow-alt-circle-right': 0x035a,
            'arrow-alt-circle-up': 0x035b,
            'arrow-circle-down': 0x00ab,
            'arrow-circle-left': 0x00a8,
            'arrow-circle-right': 0x00a9,
            'arrow-circle-up': 0x00aa,
            'arrow-down': 0x0063,
            'arrow-left': 0x0060,
            'arrow-right': 0x0061,
            'arrow-up': 0x0062,
            'arrows-alt-h': 0x00b2,
            'arrows-alt-v': 0x0337,
            'arrows-alt': 0x0338,
            'assistive-listening-systems': 0x02a2,
            'asterisk': 0x0069,
            'at': 0x01fa,
            'audio-description': 0x029e,
            'backward': 0x004a,
            'balance-scale': 0x024e,
            'ban': 0x005e,
            'barcode': 0x002a,
            'bars': 0x00c9,
            'baseball-ball': 0x0433,
            'basketball-ball': 0x0434,
            'bath': 0x02cd,
            'battery-empty': 0x0244,
            'battery-full': 0x0240,
            'battery-half': 0x0242,
            'battery-quarter': 0x0243,
            'battery-three-quarters': 0x0241,
            'bed': 0x0236,
            'beer': 0x00fc,
            'bell-slash': 0x00f3,
            'bell': 0x01f6,
            'bicycle': 0x0206,
            'binoculars': 0x01e5,
            'birthday-cake': 0x01fd,
            'blind': 0x029d,
            'bold': 0x0032,
            'bolt': 0x00e7,
            'bomb': 0x01e2,
            'book': 0x002d,
            'bookmark': 0x002e,
            'bowling-ball': 0x0436,
            'braille': 0x02a1,
            'briefcase': 0x00b1,
            'bug': 0x0188,
            'building': 0x01ad,
            'bullhorn': 0x00a1,
            'bullseye': 0x0140,
            'calculator': 0x01ec,
            'calendar-alt': 0x0133,
            'calendar-check': 0x0073,
            'calendar-minus': 0x0274,
            'calendar-plus': 0x0272,
            'calendar-times': 0x0271,
            'calendar': 0x0273,
            'camera-retro': 0x0030,
            'camera': 0x0083,
            'caret-down': 0x00d7,
            'caret-left': 0x00d9,
            'caret-right': 0x00da,
            'caret-square-down': 0x0150,
            'caret-square-left': 0x0191,
            'caret-square-right': 0x0152,
            'caret-square-up': 0x0151,
            'caret-up': 0x00d8,
            'cart-arrow-down': 0x0218,
            'cart-plus': 0x0217,
            'certificate': 0x00a3,
            'chart-area': 0x01fe,
            'chart-bar': 0x0080,
            'chart-line': 0x0201,
            'chart-pie': 0x0200,
            'check-circle': 0x000c,
            'check-square': 0x0058,
            'check': 0x014a,
            'chess-bishop': 0x0439,
            'chess-board': 0x043a,
            'chess-king': 0x043c,
            'chess-knight': 0x043f,
            'chess-pawn': 0x0441,
            'chess-queen': 0x0443,
            'chess-rook': 0x0445,
            'chess': 0x0447,
            'chevron-circle-down': 0x013a,
            'chevron-circle-left': 0x0137,
            'chevron-circle-right': 0x0138,
            'chevron-circle-up': 0x0139,
            'chevron-down': 0x0078,
            'chevron-left': 0x0053,
            'chevron-right': 0x0054,
            'chevron-up': 0x0077,
            'child': 0x01ae,
            'circle-notch': 0x0111,
            'circle': 0x01ce,
            'clipboard': 0x0328,
            'clock': 0x0017,
            'clone': 0x024d,
            'closed-captioning': 0x020a,
            'cloud-download-alt': 0x00c2,
            'cloud-upload-alt': 0x0381,
            'cloud': 0x0382,
            'code-branch': 0x0121,
            'code': 0x0126,
            'coffee': 0x00f4,
            'cog': 0x0013,
            'cogs': 0x0085,
            'columns': 0x00db,
            'comment-alt': 0x0075,
            'comment': 0x027a,
            'comments': 0x0086,
            'compass': 0x014e,
            'compress': 0x0066,
            'copy': 0x00c5,
            'copyright': 0x01f9,
            'credit-card': 0x009d,
            'crop': 0x0125,
            'crosshairs': 0x005b,
            'cube': 0x01b2,
            'cubes': 0x01b3,
            'cut': 0x00c4,
            'database': 0x01c0,
            'deaf': 0x02a4,
            'desktop': 0x0108,
            'dollar-sign': 0x0155,
            'dot-circle': 0x0192,
            'download': 0x0019,
            'edit': 0x0044,
            'eject': 0x0052,
            'ellipsis-h': 0x0141,
            'ellipsis-v': 0x0142,
            'envelope-open': 0x00e0,
            'envelope-square': 0x02b6,
            'envelope': 0x0199,
            'eraser': 0x012d,
            'euro-sign': 0x0153,
            'exchange-alt': 0x0362,
            'exclamation-circle': 0x012a,
            'exclamation-triangle': 0x006a,
            'exclamation': 0x0071,
            'expand-arrows-alt': 0x0065,
            'expand': 0x031e,
            'external-link-alt': 0x035d,
            'external-link-square-alt': 0x0360,
            'eye-dropper': 0x006e,
            'eye-slash': 0x01fb,
            'eye': 0x0070,
            'fast-backward': 0x0049,
            'fast-forward': 0x0050,
            'female': 0x0182,
            'file': 0x01c2,
            'film': 0x0008,
            'filter': 0x00b0,
            'fire-extinguisher': 0x006d,
            'fire': 0x0134,
            'flag-checkered': 0x0024,
            'flag': 0x011e,
            'flask': 0x00c3,
            'folder-open': 0x007b,
            'folder': 0x007c,
            'font': 0x0031,
            'football-ball': 0x044e,
            'forward': 0x004e,
            'frown': 0x0119,
            'futbol': 0x01e3,
            'gamepad': 0x011b,
            'gavel': 0x00e3,
            'gem': 0x03a5,
            'genderless': 0x022d,
            'gift': 0x006b,
            'glass-martini': 0x0000,
            'globe': 0x00ac,
            'golf-ball': 0x0450,
            'graduation-cap': 0x019d,
            'h-square': 0x00fd,
            'hand-lizard': 0x0258,
            'hand-paper': 0x0256,
            'hand-peace': 0x025b,
            'hand-point-down': 0x00a7,
            'hand-point-left': 0x00a5,
            'hand-point-right': 0x00a4,
            'hand-point-up': 0x00a6,
            'hand-pointer': 0x025a,
            'hand-rock': 0x0255,
            'hand-scissors': 0x0257,
            'hand-spock': 0x0259,
            'handshake': 0x02b5,
            'hashtag': 0x0292,
            'hdd': 0x00a0,
            'heading': 0x01dc,
            'headphones': 0x0025,
            'heart': 0x0004,
            'heartbeat': 0x021e,
            'history': 0x01da,
            'hockey-puck': 0x0453,
            'home': 0x0015,
            'hospital': 0x00f8,
            'hourglass-end': 0x0254,
            'hourglass-half': 0x0253,
            'hourglass-start': 0x0252,
            'hourglass': 0x0251,
            'i-cursor': 0x0246,
            'id-badge': 0x02c1,
            'id-card': 0x02c2,
            'image': 0x003e,
            'images': 0x0302,
            'inbox': 0x001c,
            'indent': 0x003c,
            'industry': 0x0275,
            'info-circle': 0x0129,
            'info': 0x005a,
            'italic': 0x0033,
            'key': 0x0084,
            'keyboard': 0x011c,
            'language': 0x01ab,
            'laptop': 0x0109,
            'leaf': 0x006c,
            'lemon': 0x0094,
            'level-down-alt': 0x03be,
            'level-up-alt': 0x03bf,
            'life-ring': 0x01cd,
            'lightbulb': 0x00eb,
            'link': 0x00c1,
            'lira-sign': 0x0195,
            'list-alt': 0x003a,
            'list-ol': 0x0022,
            'list-ul': 0x00cb,
            'list': 0x00ca,
            'location-arrow': 0x0124,
            'lock-open': 0x0023,
            'lock': 0x03c1,
            'long-arrow-alt-down': 0x0309,
            'long-arrow-alt-left': 0x030a,
            'long-arrow-alt-right': 0x030b,
            'long-arrow-alt-up': 0x030c,
            'low-vision': 0x02a8,
            'magic': 0x00d0,
            'magnet': 0x0076,
            'male': 0x0183,
            'map-pin': 0x03c5,
            'map-signs': 0x0276,
            'mars-double': 0x0222,
            'mars-stroke-h': 0x0227,
            'mars-stroke-v': 0x0229,
            'mars-stroke': 0x022b,
            'mars': 0x022a,
            'medkit': 0x00fa,
            'meh': 0x011a,
            'mercury': 0x0223,
            'microchip': 0x02db,
            'microphone-slash': 0x0130,
            'microphone': 0x0131,
            'minus-circle': 0x0068,
            'minus-square': 0x0056,
            'minus': 0x0146,
            'mobile-alt': 0x010b,
            'mobile': 0x03cd,
            'money-bill-alt': 0x03d1,
            'moon': 0x0186,
            'motorcycle': 0x021c,
            'mouse-pointer': 0x0245,
            'music': 0x0001,
            'neuter': 0x022c,
            'newspaper': 0x01ea,
            'object-group': 0x0247,
            'object-ungroup': 0x0248,
            'outdent': 0x003b,
            'paint-brush': 0x01fc,
            'paper-plane': 0x01d8,
            'paperclip': 0x00c6,
            'paragraph': 0x01dd,
            'paste': 0x00ea,
            'pause-circle': 0x004c,
            'pause': 0x028b,
            'paw': 0x01b0,
            'pen-square': 0x014b,
            'pencil-alt': 0x0303,
            'percent': 0x0295,
            'phone-square': 0x0095,
            'phone-volume': 0x0098,
            'phone': 0x02a0,
            'plane': 0x0072,
            'play-circle': 0x004b,
            'play': 0x0144,
            'plug': 0x01e6,
            'plus-circle': 0x0067,
            'plus-square': 0x0055,
            'plus': 0x00fe,
            'podcast': 0x02ce,
            'pound-sign': 0x0154,
            'power-off': 0x0011,
            'print': 0x002f,
            'puzzle-piece': 0x012e,
            'qrcode': 0x0029,
            'question-circle': 0x0128,
            'question': 0x0059,
            'quidditch': 0x0458,
            'quote-left': 0x010d,
            'quote-right': 0x010e,
            'random': 0x0074,
            'recycle': 0x01b8,
            'redo-alt': 0x001e,
            'redo': 0x02f9,
            'registered': 0x025d,
            'reply-all': 0x03e5,
            'reply': 0x0122,
            'retweet': 0x0079,
            'road': 0x0018,
            'rocket': 0x0135,
            'rss-square': 0x009e,
            'rss': 0x0143,
            'ruble-sign': 0x0158,
            'rupee-sign': 0x0156,
            'save': 0x00c7,
            'search-minus': 0x0002,
            'search-plus': 0x0010,
            'search': 0x000e,
            'server': 0x0233,
            'share-alt-square': 0x0064,
            'share-alt': 0x01e0,
            'share-square': 0x01e1,
            'share': 0x014d,
            'shekel-sign': 0x020b,
            'shield-alt': 0x03ed,
            'ship': 0x021a,
            'shopping-bag': 0x0290,
            'shopping-basket': 0x0291,
            'shopping-cart': 0x007a,
            'shower': 0x02cc,
            'sign-in-alt': 0x02f6,
            'sign-language': 0x02a7,
            'sign-out-alt': 0x02f5,
            'signal': 0x0012,
            'sitemap': 0x00e8,
            'sliders-h': 0x01de,
            'smile': 0x0118,
            'snowflake': 0x02dc,
            'sort-alpha-down': 0x00dc,
            'sort-alpha-up': 0x015d,
            'sort-amount-down': 0x015e,
            'sort-amount-up': 0x0160,
            'sort-down': 0x0161,
            'sort-numeric-down': 0x00dd,
            'sort-numeric-up': 0x0162,
            'sort-up': 0x0163,
            'sort': 0x00de,
            'space-shuttle': 0x0197,
            'spinner': 0x0110,
            'square-full': 0x00c8,
            'square': 0x045c,
            'star-half': 0x0005,
            'star': 0x0089,
            'step-backward': 0x0048,
            'step-forward': 0x0051,
            'stethoscope': 0x00f1,
            'sticky-note': 0x0249,
            'stop-circle': 0x004d,
            'stop': 0x028d,
            'stopwatch': 0x02f2,
            'street-view': 0x021d,
            'strikethrough': 0x00cc,
            'subscript': 0x012c,
            'subway': 0x0239,
            'suitcase': 0x00f2,
            'sun': 0x0185,
            'superscript': 0x012b,
            'sync-alt': 0x0021,
            'sync': 0x02f1,
            'table-tennis': 0x00ce,
            'table': 0x045d,
            'tablet-alt': 0x010a,
            'tablet': 0x03fa,
            'tachometer-alt': 0x03fd,
            'tag': 0x002b,
            'tags': 0x002c,
            'tasks': 0x00ae,
            'taxi': 0x01ba,
            'terminal': 0x0120,
            'text-height': 0x0034,
            'text-width': 0x0035,
            'th-large': 0x000a,
            'th-list': 0x0009,
            'th': 0x000b,
            'thermometer-empty': 0x02cb,
            'thermometer-full': 0x02c7,
            'thermometer-half': 0x02c9,
            'thermometer-quarter': 0x02ca,
            'thermometer-three-quarters': 0x02c8,
            'thumbs-down': 0x0165,
            'thumbs-up': 0x0164,
            'thumbtack': 0x008d,
            'ticket-alt': 0x03ff,
            'times-circle': 0x000d,
            'times': 0x0057,
            'tint': 0x0043,
            'toggle-off': 0x0204,
            'toggle-on': 0x0205,
            'trademark': 0x025c,
            'train': 0x0238,
            'transgender-alt': 0x0224,
            'transgender': 0x0225,
            'trash-alt': 0x01f8,
            'trash': 0x02ed,
            'tree': 0x01bb,
            'trophy': 0x0091,
            'truck': 0x00d1,
            'tty': 0x01e4,
            'tv': 0x026c,
            'umbrella': 0x00e9,
            'underline': 0x00cd,
            'undo-alt': 0x00e2,
            'undo': 0x02ea,
            'universal-access': 0x029a,
            'university': 0x019c,
            'unlink': 0x0127,
            'unlock-alt': 0x009c,
            'unlock': 0x013e,
            'upload': 0x0093,
            'user-circle': 0x0007,
            'user-md': 0x02bd,
            'user-plus': 0x00f0,
            'user-secret': 0x0234,
            'user-times': 0x021b,
            'user': 0x0235,
            'users': 0x00c0,
            'utensil-spoon': 0x02e5,
            'utensils': 0x02e7,
            'venus-double': 0x0221,
            'venus-mars': 0x0226,
            'venus': 0x0228,
            'video': 0x003d,
            'volleyball-ball': 0x045f,
            'volume-down': 0x0027,
            'volume-off': 0x0026,
            'volume-up': 0x0028,
            'wheelchair': 0x0193,
            'wifi': 0x01eb,
            'window-close': 0x0410,
            'window-maximize': 0x02d0,
            'window-minimize': 0x02d1,
            'window-restore': 0x02d2,
            'won-sign': 0x0159,
            'wrench': 0x00ad,
            'yen-sign': 0x0157
          }
        }
      },

    },

    // 3. Copy the source SVGs into the font folders
    copy: {
      main: {
        files: [
          // includes files within path
          {expand: true, cwd: 'source/chemistry/', src: ['**'], dest: 'EBI-Chemistry/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/conceptual/', src: ['**'], dest: 'EBI-Conceptual/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/fileformats/', src: ['**'], dest: 'EBI-FileFormats/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/functional/', src: ['**'], dest: 'EBI-Functional/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/generic/', src: ['**'], dest: 'EBI-Generic/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/social/', src: ['**'], dest: 'EBI-SocialMedia/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/species/', src: ['**'], dest: 'EBI-Species/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }}
        ],
      },
    },
    // 4. Make the PNGs
    //    (and compiled CSS files for poteintal future use)
    grunticon: {
      chemistry: {
          files: [{
              expand: true,
              cwd: 'EBI-Chemistry/static/svg',
              src: ['*.svg'],
              dest: "EBI-Chemistry/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      conceptual: {
          files: [{
              expand: true,
              cwd: 'EBI-Conceptual/static/svg',
              src: ['*.svg'],
              dest: "EBI-Conceptual/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      fileformats: {
          files: [{
              expand: true,
              cwd: 'EBI-FileFormats/static/svg',
              src: ['*.svg'],
              dest: "EBI-FileFormats/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      functional: {
          files: [{
              expand: true,
              cwd: 'EBI-Functional/static/svg',
              src: ['*.svg'],
              dest: 'EBI-Functional/static'
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      generic: {
          files: [{
              expand: true,
              cwd: 'EBI-Generic/static/svg',
              src: ['*.svg'],
              dest: 'EBI-Generic/static'
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      social: {
          files: [{
              expand: true,
              cwd: 'EBI-SocialMedia/static/svg',
              src: ['*.svg'],
              dest: "EBI-SocialMedia/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      species: {
          files: [{
              expand: true,
              cwd: 'EBI-Species/static/svg',
              src: ['*.svg'],
              dest: "EBI-Species/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
    },
    // 5. Combine the built webfont previews into a global template
    includes: {
      files: {
        debug: true,
        src: [
          'templates/partial.html',
          'templates/fonts.css'
        ],
        dest: '.', // Destination directory
        flatten: true,
        cwd: '.',
        options: {
          // silent: true,
          // banner: '<!-- To be consumed by the EBI Style Lab -->',
          includePath: [
            'EBI-Chemistry/fonts/',
            'EBI-Conceptual/fonts/',
            'EBI-Common/fonts/',
            'EBI-FileFormats/fonts/',
            'EBI-Functional/fonts/',
            'EBI-Generic/fonts/',
            'EBI-SocialMedia/fonts/',
            'EBI-Species/fonts/'
          ],

        }
      }
    }

    // grunticon: {
    //     all: {
    //         files: [{
    //             expand: true,
    //             cwd: 'icons/source',
    //             src: ['*.svg', '*.png'],
    //             dest: "icons/output"
    //         }],
    //         options: {
    //           // enhanceSVG: true,
    //           "previewTemplate": "templates/preview.hbs",
    //           "template":        "templates/css.hbs",
    //           colors: {
    //             "white": "#ffffff"
    //           },
    //           customselectors: {
    //             "species-ferret": [".icon.icon-species[data-icon=\"!\"]"],
    //             "species-bee": [".icon.icon-species[data-icon=\"$\"]"],
    //             "species-brachypodium": [".icon.icon-species[data-icon=\"%\"]"],
    //             "species-tick": [".icon.icon-species[data-icon=\"&\"]"],
    //             "species-bat": [".icon.icon-species[data-icon=\"(\"]"],
    //             "species-tomatoes": [".icon.icon-species[data-icon=\")\"]"],
    //             "species-orangutan": [".icon.icon-species[data-icon=\"*\"]"],
    //             "species-amoeba": [".icon.icon-species[data-icon=\"0\"]"],
    //             "species-mosquito": [".icon.icon-species[data-icon=\"1\"]"],
    //             "species-diatom": [".icon.icon-species[data-icon=\"2\"]"],
    //             "species-kangaroo-rat": [".icon.icon-species[data-icon=\"3\"]"],
    //             "species-louse": [".icon.icon-species[data-icon=\"4\"]"],
    //             "species-barley": [".icon.icon-species[data-icon=\"5\"]"],
    //             "species-rice": [".icon.icon-species[data-icon=\"6\"]"],
    //             "species-anolis": [".icon.icon-species[data-icon=\"7\"]"],
    //             "species-papio": [".icon.icon-species[data-icon=\"8\"]"],
    //             "species-monodelphis": [".icon.icon-species[data-icon=\"9\"]"],
    //             "species-plasmodium": [".icon.icon-species[data-icon=\"@\"]"],
    //             "species-cat": [".icon.icon-species[data-icon=\"A\"]"],
    //             "species-brassica": [".icon.icon-species[data-icon=\"B\"]"],
    //             "species-cow": [".icon.icon-species[data-icon=\"C\"]"],
    //             "species-dolphin": [".icon.icon-species[data-icon=\"D\"]"],
    //             "species-pufferfish": [".icon.icon-species[data-icon=\"E\"]"],
    //             "species-fly": [".icon.icon-species[data-icon=\"F\"]"],
    //             "species-gorilla": [".icon.icon-species[data-icon=\"G\"]"],
    //             "species-human": [".icon.icon-species[data-icon=\"H\"]"],
    //             "species-squirrel": [".icon.icon-species[data-icon=\"I\"]"],
    //             "species-ecoli": [".icon.icon-species[data-icon=\"L\"]"],
    //             "species-mouse": [".icon.icon-species[data-icon=\"M\"]"],
    //             "species-mouse-lemur": [".icon.icon-species[data-icon=\"N\"]"],
    //             "species-grapes": [".icon.icon-species[data-icon=\"0\"]"],
    //             "species-plant": [".icon.icon-species[data-icon=\"P\"]"],
    //             "species-shrew": [".icon.icon-species[data-icon=\"Q\"]"],
    //             "species-rat": [".icon.icon-species[data-icon=\"R\"]"],
    //             "species-spider": [".icon.icon-species[data-icon=\"S\"]"],
    //             "species-platypus": [".icon.icon-species[data-icon=\"U\"]"],
    //             "species-c-elegans": [".icon.icon-species[data-icon=\"W\"]"],
    //             "species-yeast": [".icon.icon-species[data-icon=\"Y\"]"],
    //             "species-zebrafish": [".icon.icon-species[data-icon=\"Z\"]"],
    //             "species-glycinemax": [".icon.icon-species[data-icon=\"^\"]"],
    //             "species-alpaca": [".icon.icon-species[data-icon=\"a\"]"],
    //             "species-bug": [".icon.icon-species[data-icon=\"b\"]"],
    //             "species-corn": [".icon.icon-species[data-icon=\"d\"]"],
    //             "species-dog": [".icon.icon-species[data-icon=\"d\"]"],
    //             "species-elephant": [".icon.icon-species[data-icon=\"e\"]"],
    //             "species-frog": [".icon.icon-species[data-icon=\"f\"]"],
    //             "species-guinea-pig": [".icon.icon-species[data-icon=\"g\"]"],
    //             "species-horse": [".icon.icon-species[data-icon=\"h\"]"],
    //             "species-chimpanzee": [".icon.icon-species[data-icon=\"i\"]"],
    //             "species-chicken": [".icon.icon-species[data-icon=\"k\"]"],
    //             "species-armadillo": [".icon.icon-species[data-icon=\"l\"]"],
    //             "species-finch": [".icon.icon-species[data-icon=\"n\"]"],
    //             "species-hedgehog": [".icon.icon-species[data-icon=\"o\"]"],
    //             "species-pig": [".icon.icon-species[data-icon=\"p\"]"],
    //             "species-monkey": [".icon.icon-species[data-icon=\"r\"]"],
    //             "species-scorpion": [".icon.icon-species[data-icon=\"s\"]"],
    //             "species-rabbit": [".icon.icon-species[data-icon=\"t\"]"],
    //             "species-fungus": [".icon.icon-species[data-icon=\"u\"]"],
    //             "species-virus": [".icon.icon-species[data-icon=\"v\"]"],
    //             "species-wallaby": [".icon.icon-species[data-icon=\"w\"]"],
    //             "species-sheep": [".icon.icon-species[data-icon=\"x\"]"],
    //             "species-aspergillus": [".icon.icon-species[data-icon=\"£\"]"],
    //             "*": [".icon[data-icon=\"$1\"]", ".icon.icon-$1"]
    //           }
    //         }
    //     }
    // }
  });
  grunt.registerTask('default', ['svgmin','webfont','grunticon','copy','includes']);

};
