var path = require('path');

var version = '1.3'; // the version from the git repo branch

module.exports = function(grunt) {
  'use strict';

  grunt.loadNpmTasks('grunt-svgmin');
  grunt.loadNpmTasks('grunt-webfont');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-grunticon');
  grunt.loadNpmTasks('grunt-includes');

  grunt.initConfig({
    // 1. We want to minify the source SVG icons
    // TODO:
    // - add compression for common source folders
    // - remove generic, functional, social as those are archived and won't be changed
    svgmin: {
      chemistry: {
        files: [{
          expand: true,
          cwd: 'source/chemistry',
          src: ['*.svg'],
          dest: 'source/chemistry'
        }]
      },
      conceptual: {
        files: [{
          expand: true,
          cwd: 'source/conceptual',
          src: ['*.svg'],
          dest: 'source/conceptual'
        }]
      },
      fileformats: {
        files: [{
          expand: true,
          cwd: 'source/fileformats',
          src: ['*.svg'],
          dest: 'source/fileformats'
        }]
      },
      functional: {
        files: [{
          expand: true,
          cwd: 'source/functional',
          src: ['*.svg'],
          dest: 'source/functional'
        }]
      },
      generic: {
        files: [{
          expand: true,
          cwd: 'source/generic',
          src: ['*.svg'],
          dest: 'source/generic'
        }]
      },
      social: {
        files: [{
          expand: true,
          cwd: 'source/social',
          src: ['*.svg'],
          dest: 'source/social'
        }]
      },
      species: {
        files: [{
          expand: true,
          cwd: 'source/species',
          src: ['*.svg'],
          dest: 'source/species'
        }]
      }
    },
    // 2. Build the icon fonts
    //    and we want to specify the letter codes
    webfont: {
      'EBI-Species': {
        src: 'source/species/*.svg',
        dest: 'EBI-Species/fonts',
        // destCss: 'EBI-Species',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-Species',
          fontFamilyName: 'EBI-Species',
          fontFilename: 'EBI-Species',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-species',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'ferret': 0x0021,
            'bee': 0x0024,
            'brachypodium': 0x0025,
            'tick': 0x0026,
            'bat': 0x0028,
            'tomatoes': 0x0029,
            'orangutan': 0x002a,
            'amoeba': 0x0030,
            'mosquito': 0x0031,
            'diatom': 0x0032,
            'kangaroo-rat': 0x0033,
            'louse': 0x0034,
            'barley': 0x0035,
            'rice': 0x0036,
            'anolis': 0x0037,
            'papio': 0x0038,
            'monodelphis': 0x0039,
            'plasmodium': 0x0040,
            'cat': 0x0041,
            'brassica': 0x0042,
            'cow': 0x0043,
            'dolphin': 0x0044,
            'pufferfish': 0x0045,
            'fly': 0x0046,
            'gorilla': 0x0047,
            'human': 0x0048,
            'squirrel': 0x0049,
            'ecoli': 0x004c,
            'mouse': 0x004d,
            'mouse-lemur': 0x004e,
            'grapes': 0x004f,
            'plant': 0x0050,
            'shrew': 0x0051,
            'rat': 0x0052,
            'spider': 0x0053,
            'platypus': 0x0055,
            'c-elegans': 0x0057,
            'yeast': 0x0059,
            'zebrafish': 0x005a,
            'glycinemax': 0x005e,
            'alpaca': 0x0061,
            'bug': 0x0062,
            'corn': 0x0063,
            'dog': 0x0064,
            'elephant': 0x0065,
            'frog': 0x0066,
            'guinea-pig': 0x0067,
            'horse': 0x0068,
            'chimpanzee': 0x0069,
            'chicken': 0x006b,
            'armadillo': 0x006c,
            'finch': 0x006e,
            'hedgehog': 0x006f,
            'pig': 0x0070,
            'monkey': 0x0072,
            'scorpion': 0x0073,
            'rabbit': 0x0074,
            'fungus': 0x0075,
            'virus': 0x0076,
            'wallaby': 0x0077,
            'sheep': 0x0078,
            'aspergillus': 0x00a3,
            'goat': 0x006d,
            'snail': 0x0027,
            'ray': 0x002b
          }
        }
      },
      'EBI-SocialMedia': {
        src: 'source/social/*.svg',
        dest: 'EBI-SocialMedia/fonts',
        // destCss: 'EBI-SocialMedia',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-SocialMedia',
          fontFamilyName: 'EBI-SocialMedia',
          fontFilename: 'EBI-SocialMedia',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-socialmedia',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'android': 0x0061,
            'apple': 0x0041,
            'blogger': 0x0042,
            'facebook': 0x0046,
            'flickr': 0x0066,
            'github': 0x0067,
            'googleplus': 0x0047,
            'linkedin': 0x004c,
            'linux': 0x0058,
            'orcid': 0x004f,
            'rss': 0x0052,
            'skype': 0x0073,
            'slideshare': 0x0053,
            'twitter': 0x0054,
            'vimeo': 0x0056,
            'weibo': 0x0057,
            'windows': 0x0077,
            'wordpress': 0x0050,
            'youtube': 0x0059
          }
        }
      },
      'EBI-Generic': {
        src: 'source/generic/*.svg',
        dest: 'EBI-Generic/fonts',
        // destCss: 'EBI-Generic',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-Generic',
          fontFamilyName: 'EBI-Generic',
          fontFilename: 'EBI-Generic',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-generic',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'accommodation': 0x0061,
            'alert': 0x006c,
            'alumni': 0x0041,
            'announcement': 0x0055,
            'basket': 0x0062,
            'beta': 0x003e,
            'bike': 0x0033,
            'biotech': 0x0042,
            'bus': 0x0031,
            'calendar': 0x0072,
            'camera': 0x0021,
            'car': 0x0032,
            'careers': 0x0063,
            'classification': 0x0065,
            'clock': 0x007b,
            'contact': 0x0043,
            'crosslink': 0x0064,
            'database': 0x0044,
            'discuss': 0x005c,
            'documentation': 0x003b,
            'drug': 0x0075,
            'elixir': 0x0025,
            'email': 0x0045,
            'embl': 0x0026,
            'external-link': 0x0078,
            'external-systems': 0x0079,
            'face-to-face': 0x0066,
            'find-us': 0x005d,
            'funding': 0x0046,
            'graph': 0x0067,
            'group': 0x007d,
            'gtls': 0x0047,
            'health': 0x0068,
            'help': 0x003f,
            'home': 0x0048,
            'industry': 0x0049,
            'info': 0x0069,
            'link': 0x004c,
            'location': 0x005b,
            'lovedata': 0x006f,
            'mailing-list': 0x006d,
            'math': 0x0076,
            'meet-us': 0x004d,
            'mobile-device': 0x002f,
            'new': 0x003c,
            'newcomers': 0x006e,
            'news': 0x004e,
            'nutraceuticals': 0x0022,
            'open-day': 0x004f,
            'piechart': 0x0070,
            'plane': 0x0034,
            'publication': 0x0050,
            'research': 0x0029,
            'resource': 0x0052,
            'reviewed-data': 0x0071,
            'services': 0x0028,
            'steps': 0x0023,
            'support': 0x0073,
            'systems': 0x0053,
            'test': 0x0030,
            'text-mining': 0x0058,
            'toolkit': 0x003a,
            'train': 0x0037,
            'training': 0x0054,
            'tutorial': 0x0074,
            'unreviewed-data': 0x0051,
            'video': 0x0056,
            'walk': 0x0036
          }
        }
      },
      'EBI-Functional': {
        src: 'source/functional/*.svg',
        dest: 'EBI-Functional/fonts',
        // destCss: 'EBI-Functional',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-Functional',
          fontFamilyName: 'EBI-Functional',
          fontFilename: 'EBI-Functional',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-functional',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'add': 0x002b,
            'add-job': 0x0029,
            'add-user': 0x0037,
            'align': 0x0069,
            'analyse': 0x0041,
            'analyse-percent_0': 0x0042,
            'analyse-percent_40': 0x0043,
            'analyse-percent_100': 0x0045,
            'analyse-graph': 0x007a,
            'approve': 0x002f,
            'approved-job': 0x0028,
            'attach': 0x0061,
            'browse': 0x0062,
            'close': 0x0078,
            'collapse': 0x0077,
            'collapse-closed': 0x0039,
            'collapse-open': 0x0038,
            'compare': 0x004f,
            'crop': 0x005c,
            'cut': 0x0063,
            'database-submit': 0x0044,
            'delete': 0x0064,
            'download': 0x003d,
            'down-page': 0x2b07,
            'edit': 0x0065,
            'edit-user': 0x0035,
            'expand': 0x0075,
            'filter': 0x0066,
            'first-page': 0x005b,
            'fullscreen': 0x0046,
            'hierarchy': 0x0068,
            'last-page': 0x005d,
            'like': 0x006b,
            'lock': 0x004c,
            'login': 0x006c,
            'mapping': 0x0030,
            'menu': 0x004d,
            'move': 0x006d,
            'next-page': 0x003e,
            'play': 0x0076,
            'previous-page': 0x003c,
            'print': 0x0050,
            'redo': 0x007d,
            'refresh': 0x0052,
            'remove': 0x002d,
            'remove-user': 0x0036,
            'save': 0x0053,
            'scaleable': 0x0059,
            'search': 0x0031,
            'search-document': 0x006a,
            'send': 0x006e,
            'settings': 0x0073,
            'share': 0x0072,
            'stop': 0x006f,
            'submit': 0x005f,
            'target': 0x0054,
            'tool': 0x0074,
            'unassigned-job': 0x002a,
            'undo': 0x007b,
            'unlock': 0x0055,
            'up-page': 0x2b06,
            'view': 0x0034,
            'zoom-in': 0x0033,
            'zoom-out': 0x0032
          }
        }
      },
      'EBI-Conceptual': {
        src: 'source/conceptual/*.svg',
        dest: 'EBI-Conceptual/fonts',
        // destCss: 'EBI-Conceptual',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-Conceptual',
          fontFamilyName: 'EBI-Conceptual',
          fontFilename: 'EBI-Conceptual',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-conceptual',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'chemical': 0x0062,
            'cross-domain': 0x0063,
            'dna': 0x0064,
            'expression': 0x0067,
            'literature': 0x006c,
            'ontology': 0x006f,
            'proteins': 0x0050,
            'structures': 0x0073,
            'structures-3d': 0x0053,
            'systems': 0x0079
          }
        }
      },
      'EBI-FileFormats': {
        src: 'source/fileformats/*.svg',
        dest: 'EBI-FileFormats/fonts',
        // destCss: 'EBI-FileFormats',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-FileFormats',
          fontFamilyName: 'EBI-FileFormats',
          fontFilename: 'EBI-FileFormats',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-fileformats',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'ZIP': 0x005a,
            'Postscript': 0x0033,
            'XML': 0x0078,
            'DOC': 0x0064,
            'TXT': 0x0074,
            'TSV': 0x0076,
            'SDF': 0x0073,
            'RXN': 0x0058,
            'RDF_XML': 0x0044,
            'RD': 0x0072,
            'PSI-MI_XML': 0x0031,
            'PSI-MI_TAB': 0x0032,
            'PDF': 0x0070,
            'OWL': 0x006f,
            'OBO': 0x004f,
            'MDL': 0x004d,
            'JSON': 0x004a,
            'IMG': 0x0049,
            'GFF': 0x0047,
            'FLAT': 0x0046,
            'FASTQ': 0x0066,
            'FASTA': 0x0061,
            'CSV': 0x0063,
            'CRAM': 0x0052,
            'CML': 0x0043,
            'BAM': 0x0042,
            'AGP': 0x0041
          }
        }
      },
      'EBI-Chemistry': {
        src: 'source/chemistry/*.svg',
        dest: 'EBI-Chemistry/fonts',
        // destCss: 'EBI-Chemistry',
        options: {
          version: version,
          // ligatures: true,
          font: 'EBI-Chemistry',
          fontFamilyName: 'EBI-Chemistry',
          fontFilename: 'EBI-Chemistry',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-chemistry',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            'direction_unknown': 0x0055,
            'direction_right': 0x0072,
            'direction_left': 0x006c,
            'direction_reversible': 0x0052
          }
        }
      },
      'EBI-Common': {
        src: 'source/common/**/*.svg',
        dest: 'EBI-Common/fonts',
        // destCss: 'EBI-SocialMedia',
        options: {
          version: version,
          // ligatures: true,
          // ligatures would be really nice, but we have to get rid of hyphens
          // and there appears to be some other oddness about what renders and what
          // wont...
          // https://github.com/sapegin/grunt-webfont/issues/167
          normalize: true, // as some icons are now depeninding on keycode
          font: 'EBI-Common',
          fontFamilyName: 'EBI-Common',
          fontFilename: 'EBI-Common',
          types: 'woff,woff2,ttf',
          template: 'templates/font-individual.css',
          templateOptions: {
            baseClass: 'icon-common',
            classPrefix: 'icon-'
          },
          htmlDemoTemplate: 'templates/template-webfont.html',
          codepoints: {
            // Old social icons
            // 'android': 0x1F916,
            // 'apple': 0x1F34F,
            // 'blogger': 0x1F524,
            // 'facebook': 0x1F4D8,
            // 'flickr': 0x1F4F7,
            // 'github': 0x1F9EE,
            // 'googleplus': 0x1F4D5,
            // 'linkedin': 0x1F4C7,
            // 'linux': 0x1F193,
            // 'orcid': 0x1F4C3,
            // 'rss': 0x1F4F0,
            // 'skype': 0x1F4F3,
            // 'slideshare': 0x1F3A4,
            // 'twitter': 0x1F426,
            // 'vimeo': 0x1F39E,
            // 'weibo': 0x1F472,
            // 'windows': 0x1F3E2,
            // 'wordpress': 0x1F4D3,
            // 'youtube': 0x1F4FD,
            // // old functional icons
            // 'add': 0x002b,
            // 'add-job': 0x0029,
            // 'add-user': 0x0037,
            // 'align': 0x0069,
            // 'analyse': 0x0041,
            // 'analyse-percent_0': 0x0042,
            // 'analyse-percent_40': 0x0043,
            // 'analyse-percent_100': 0x0045,
            // 'analyse-graph': 0x007a,
            // 'approve': 0x002f,
            // 'approved-job': 0x0028,
            // 'attach': 0x0061,
            // 'browse': 0x0062,
            // 'close': 0x0078,
            // 'collapse': 0x0077,
            // 'collapse-closed': 0x0039,
            // 'collapse-open': 0x0038,
            // 'compare': 0x004f,
            // 'crop': 0x005c,
            // 'cut': 0x0063,
            // 'database-submit': 0x0044,
            // 'delete': 0x0064,
            // 'download': 0x003d,
            // 'down-page': 0x2b07,
            // 'edit': 0x0065,
            // 'edit-user': 0x0035,
            // 'expand': 0x0075,
            // 'filter': 0x0066,
            // 'first-page': 0x005b,
            // 'fullscreen': 0x0046,
            // 'hierarchy': 0x0068,
            // 'last-page': 0x005d,
            // 'like': 0x006b,
            // 'lock': 0x004c,
            // 'login': 0x006c,
            // 'mapping': 0x0030,
            // 'menu': 0x004d,
            // 'move': 0x006d,
            // 'next-page': 0x003e,
            // 'play': 0x0076,
            // 'previous-page': 0x003c,
            // 'print': 0x0050,
            // 'redo': 0x007d,
            // 'refresh': 0x0052,
            // 'remove': 0x002d,
            // 'remove-user': 0x0036,
            // 'save': 0x0053,
            // 'scaleable': 0x0059,
            // 'search': 0x0031,
            // 'search-document': 0x006a,
            // 'send': 0x006e,
            // 'settings': 0x0073,
            // 'share': 0x0072,
            // 'stop': 0x006f,
            // 'submit': 0x005f,
            // 'target': 0x0054,
            // 'tool': 0x0074,
            // 'unassigned-job': 0x002a,
            // 'undo': 0x007b,
            // 'unlock': 0x0055,
            // 'up-page': 0x2b06,
            // 'view': 0x0034,
            // 'zoom-in': 0x0033,
            // 'zoom-out': 0x0032,
            // // Old generic icons
            // 'accommodation': 0x1F3E8,
            // 'alert': 0x1F6A8,
            // 'alumni': 0x1F393,
            // 'announcement': 0x1F4DC,
            // 'basket': 0x1F6D2,
            // 'beta': 0x1F606,
            // 'bike': 0x1F6B4,
            // 'biotech': 0x1F48A,
            // 'bus': 0x1F68C,
            // 'calendar': 0x1F4C5,
            // 'camera': 0x0021,
            // 'car': 0x1F697,
            // 'careers': 0x1F3D9,
            // 'classification': 0x1F5C2,
            // 'clock': 0x23F0,
            // 'contact': 0x260E,
            // 'crosslink': 0x1F4CD,
            // 'database': 0x1F4BF,
            // 'discuss': 0x1F4AC,
            // 'documentation': 0x003b,
            // 'drug': 0x2695,
            // 'elixir': 0x0025,
            // 'email': 0x1F4E7,
            // 'embl': 0x0026,
            // 'external-link': 0x1F6AA,
            // 'external-systems': 0x0079,
            // 'face-to-face': 0x1F46F,
            // 'find-us': 0x1F9ED,
            // 'funding': 0x1F4B6,
            // 'graph': 0x0067,
            // 'group': 0x1F46A,
            // 'gtls': 0x0047,
            // 'health': 0x1F912,
            // 'help': 0x003f,
            // 'home': 0x0048,
            // 'industry': 0x1F3ED,
            // 'info': 0x2139,
            // 'link': 0x1F517,
            // 'location': 0x1F5FA,
            // 'lovedata': 0x1F91F,
            // 'mailing-list': 0x1F3E4,
            // 'math': 0x1F523,
            // 'meet-us': 0x1F46C,
            // 'mobile-device': 0x1F4F1,
            // 'new': 0x1F195,
            // 'newcomers': 0x1F68D,
            // 'news': 0x004e,
            // 'nutraceuticals': 0x0022,
            // 'open-day': 0x1F44B,
            // 'piechart': 0x0070,
            // 'plane': 0x2708,
            // 'publication': 0x1F4DA,
            // 'research': 0x1F52C,
            // 'resource': 0x1F340,
            // 'reviewed-data': 0x0071,
            // 'services': 0x1F527,
            // 'steps': 0x0023,
            // 'support': 0x1F9B8,
            // 'systems': 0x1F50C,
            // 'terms': 0x0027,
            // 'test': 0x1F97D,
            // 'text-mining': 0x0058,
            // 'toolkit': 0x003a,
            // 'train': 0x1F682,
            // 'training': 0x1F3EB,
            // 'tutorial': 0x1F4DD,
            // 'unreviewed-data': 0x0051,
            // 'video': 0x0056,
            // 'walk': 0x1F6B6,
            // // Font-Awesome
            // // Where possible these use the original Font Awesome key mappings
            // 'address-book': 0x02b9,
            // 'address-card': 0x02bb,
            // 'adjust': 0xf101,
            // 'align-center': 0xf102,
            // 'align-justify': 0xf103,
            // 'align-left': 0xf104,
            // 'align-right': 0xf105,
            // 'ambulance': 0x00f9,
            // 'american-sign-language-interpreting': 0x02a3,
            // 'anchor': 0x013d,
            // 'angle-double-down': 0x0103,
            // 'angle-double-left': 0x0100,
            // 'angle-double-right': 0x0101,
            // 'angle-double-up': 0x0102,
            // 'angle-down': 0x0107,
            // 'angle-left': 0x0104,
            // 'angle-right': 0x0105,
            // 'angle-up': 0x0106,
            // 'archive': 0x0187,
            // 'arrow-alt-circle-down': 0x0358,
            // 'arrow-alt-circle-left': 0x0359,
            // 'arrow-alt-circle-right': 0x035a,
            // 'arrow-alt-circle-up': 0x035b,
            // 'arrow-circle-down': 0x00ab,
            // 'arrow-circle-left': 0x00a8,
            // 'arrow-circle-right': 0x00a9,
            // 'arrow-circle-up': 0x00aa,
            // 'arrow-down': 0x0063,
            // 'arrow-left': 0x0060,
            // 'arrow-right': 0xf106,
            // 'arrow-up': 0xf107,
            // 'arrows-alt-h': 0x00b2,
            // 'arrows-alt-v': 0x0337,
            // 'arrows-alt': 0x0338,
            // 'assistive-listening-systems': 0x02a2,
            // 'asterisk': 0xf108,
            // 'at': 0x01fa,
            // 'audio-description': 0x029e,
            // 'backward': 0x004a,
            // 'balance-scale': 0x024e,
            // 'ban': 0x005e,
            // 'barcode': 0xf109,
            // 'bars': 0x00c9,
            // 'baseball-ball': 0x0433,
            // 'basketball-ball': 0x0434,
            // 'bath': 0x02cd,
            // 'battery-empty': 0x0244,
            // 'battery-full': 0x0240,
            // 'battery-half': 0x0242,
            // 'battery-quarter': 0x0243,
            // 'battery-three-quarters': 0x0241,
            // 'bed': 0x0236,
            // 'beer': 0x00fc,
            // 'bell-slash': 0x00f3,
            // 'bell': 0x01f6,
            // 'bicycle': 0x0206,
            // 'binoculars': 0x01e5,
            // 'birthday-cake': 0x01fd,
            // 'blind': 0x029d,
            // 'bold': 0xf128,
            // 'bolt': 0x00e7,
            // 'bomb': 0x01e2,
            // 'book': 0xf10a,
            // 'bookmark': 0x002e,
            // 'bowling-ball': 0x0436,
            // 'braille': 0x02a1,
            // 'briefcase': 0x00b1,
            // 'bug': 0x0188,
            // 'building': 0x01ad,
            // 'bullhorn': 0x00a1,
            // 'bullseye': 0x0140,
            // 'calculator': 0x01ec,
            // 'calendar-alt': 0x0133,
            // 'calendar-check': 0xf10b,
            // 'calendar-minus': 0x0274,
            // 'calendar-plus': 0x0272,
            // 'calendar-times': 0x0271,
            // 'calendar': 0x0273,
            // 'camera-retro': 0xf10c,
            // 'caret-down': 0x00d7,
            // 'caret-left': 0x00d9,
            // 'caret-right': 0x00da,
            // 'caret-square-down': 0x0150,
            // 'caret-square-left': 0x0191,
            // 'caret-square-right': 0x0152,
            // 'caret-square-up': 0x0151,
            // 'caret-up': 0x00d8,
            // 'cart-arrow-down': 0x0218,
            // 'cart-plus': 0x0217,
            // 'certificate': 0x00a3,
            // 'chart-area': 0x01fe,
            // 'chart-bar': 0x0080,
            // 'chart-line': 0x0201,
            // 'chart-pie': 0x0200,
            // 'check-circle': 0xf10d,
            // 'check-square': 0xf10e,
            // 'check': 0x014a,
            // 'chevron-circle-down': 0x013a,
            // 'chevron-circle-left': 0x0137,
            // 'chevron-circle-right': 0x0138,
            // 'chevron-circle-up': 0x0139,
            // 'chevron-down': 0xf11a,
            // 'chevron-left': 0xf12c,
            // 'chevron-right': 0xf10f,
            // 'chevron-up': 0xf11b,
            // 'child': 0x01ae,
            // 'circle-notch': 0x0111,
            // 'circle': 0x01ce,
            // 'clipboard': 0x0328,
            // 'clock': 0x0017,
            // 'clone': 0x024d,
            // 'closed-captioning': 0x020a,
            // 'cloud-download-alt': 0x00c2,
            // 'cloud-upload-alt': 0x0381,
            // 'cloud': 0x0382,
            // 'code-branch': 0x0121,
            // 'code': 0x0126,
            // 'coffee': 0x00f4,
            // 'cog': 0x0013,
            // 'cogs': 0xf110,
            // 'columns': 0x00db,
            // 'comment-alt': 0x0075,
            // 'comment': 0x027a,
            // 'comments': 0xf111,
            // 'compass': 0x014e,
            // 'compress': 0x0066,
            // 'copy': 0x00c5,
            // 'copyright': 0x01f9,
            // 'credit-card': 0x009d,
            // 'crop': 0x0125,
            // 'crosshairs': 0xf112,
            // 'cube': 0x01b2,
            // 'cubes': 0x01b3,
            // 'cut': 0x00c4,
            // 'database': 0x01c0,
            // 'deaf': 0x02a4,
            // 'desktop': 0x0108,
            // 'dollar-sign': 0x0155,
            // 'dot-circle': 0x0192,
            // 'download': 0x0019,
            // 'edit': 0xf113,
            // 'eject': 0xf114,
            // 'ellipsis-h': 0x0141,
            // 'ellipsis-v': 0x0142,
            // 'envelope-open': 0x00e0,
            // 'envelope-square': 0x02b6,
            // 'envelope': 0x0199,
            // 'eraser': 0x012d,
            // 'euro-sign': 0x0153,
            // 'exchange-alt': 0x0362,
            // 'exclamation-circle': 0x012a,
            // 'exclamation-triangle': 0xf115,
            // 'exclamation': 0xf116,
            // 'expand-arrows-alt': 0xf11c,
            // 'expand': 0x031e,
            // 'external-link-alt': 0x035d,
            // 'external-link-square-alt': 0x0360,
            // 'eye-dropper': 0xf117,
            // 'eye-slash': 0x01fb,
            // 'eye': 0xf118,
            // 'fast-backward': 0x0049,
            // 'fast-forward': 0xf11e,
            // 'female': 0x0182,
            // 'file': 0x01c2,
            // 'film': 0x0008,
            // 'filter': 0x00b0,
            // 'fire-extinguisher': 0xf119,
            // 'fire': 0x0134,
            // 'flag-checkered': 0x0024,
            // 'flag': 0x011e,
            // 'flask': 0x00c3,
            // 'folder-open': 0x007b,
            // 'folder': 0x007c,
            // 'font': 0x0031,
            // 'football-ball': 0x044e,
            // 'forward': 0xf120,
            // 'frown': 0x0119,
            // 'futbol': 0x01e3,
            // 'gamepad': 0x011b,
            // 'gavel': 0x00e3,
            // 'gem': 0x03a5,
            // 'genderless': 0x022d,
            // 'gift': 0xf11d,
            // 'glass-martini': 0x0000,
            // 'globe': 0x00ac,
            // 'golf-ball': 0x0450,
            // 'graduation-cap': 0x019d,
            // 'h-square': 0x00fd,
            // 'hand-lizard': 0x0258,
            // 'hand-paper': 0x0256,
            // 'hand-peace': 0x025b,
            // 'hand-point-down': 0x00a7,
            // 'hand-point-left': 0x00a5,
            // 'hand-point-right': 0x00a4,
            // 'hand-point-up': 0x00a6,
            // 'hand-pointer': 0x025a,
            // 'hand-rock': 0x0255,
            // 'hand-scissors': 0x0257,
            // 'hand-spock': 0x0259,
            // 'handshake': 0x02b5,
            // 'hashtag': 0x0292,
            // 'hdd': 0x00a0,
            // 'heading': 0x01dc,
            // 'headphones': 0xf11f,
            // 'heart': 0x0004,
            // 'heartbeat': 0x021e,
            // 'history': 0x01da,
            // 'hockey-puck': 0x0453,
            // 'home': 0x0015,
            // 'hospital': 0x00f8,
            // 'hourglass-end': 0x0254,
            // 'hourglass-half': 0x0253,
            // 'hourglass-start': 0x0252,
            // 'hourglass': 0x0251,
            // 'i-cursor': 0x0246,
            // 'id-badge': 0x02c1,
            // 'id-card': 0x02c2,
            // 'image': 0xf121,
            // 'images': 0xf122,
            // 'inbox': 0x001c,
            // 'indent': 0xf12d,
            // 'industry': 0x0275,
            // 'italic': 0xf123,
            // 'key': 0xf12f,
            // 'keyboard': 0x011c,
            // 'language': 0x01ab,
            // 'laptop': 0x0109,
            // 'leaf': 0xf124,
            // 'lemon': 0xf125,
            // 'level-down-alt': 0x03be,
            // 'level-up-alt': 0x03bf,
            // 'lightbulb': 0x00eb,
            // 'link': 0x00c1,
            // 'lira-sign': 0x0195,
            // 'list-ol': 0xf127,
            // 'list-ul': 0x00cb,
            // 'list': 0x00ca,
            // 'location-arrow': 0x0124,
            // 'long-arrow-alt-down': 0x0309,
            // 'long-arrow-alt-left': 0x030a,
            // 'long-arrow-alt-right': 0x030b,
            // 'long-arrow-alt-up': 0x030c,
            // 'low-vision': 0xf129,
            // 'magic': 0x00d0,
            // 'magnet': 0x0076,
            // 'male': 0x0183,
            // 'map-pin': 0x03c5,
            // 'map-signs': 0x0276,
            // 'mars-double': 0x0222,
            // 'mars-stroke-h': 0x0227,
            // 'mars-stroke-v': 0x0229,
            // 'mars-stroke': 0x022b,
            // 'mars': 0x022a,
            // 'medkit': 0x00fa,
            // 'meh': 0x011a,
            // 'mercury': 0x0223,
            // 'microchip': 0x02db,
            // 'microphone-slash': 0x0130,
            // 'microphone': 0x0131,
            // 'minus-circle': 0xf12a,
            // 'minus-square': 0x0056,
            // 'minus': 0x0146,
            // 'mobile-alt': 0x010b,
            // 'mobile': 0x03cd,
            // 'money-bill-alt': 0x03d1,
            // 'moon': 0x0186,
            // 'motorcycle': 0x021c,
            // 'mouse-pointer': 0x0245,
            // 'music': 0x0001,
            // 'neuter': 0x022c,
            // 'newspaper': 0x01ea,
            // 'object-group': 0x0247,
            // 'object-ungroup': 0x0248,
            // 'outdent': 0xf12b,
            // 'paint-brush': 0x01fc,
            // 'paper-plane': 0x01d8,
            // 'paperclip': 0x00c6,
            // 'paragraph': 0x01dd,
            // 'paste': 0x00ea,
            // 'pause-circle': 0x004c,
            // 'pause': 0x028b,
            // 'paw': 0x01b0,
            // 'pen-square': 0x014b,
            // 'pencil-alt': 0x0303,
            // 'percent': 0x0295,
            // 'phone': 0x02a0,
            // 'plane': 0x0072,
            // 'play-circle': 0x004b,
            // 'play': 0x0144,
            // 'plug': 0x01e6,
            // 'plus-circle': 0xf12e,
            // 'plus-square': 0x0055,
            // 'plus': 0x00fe,
            // 'podcast': 0x02ce,
            // 'pound-sign': 0x0154,
            // 'power-off': 0x0011,
            // 'print': 0xf133,
            // 'puzzle-piece': 0x012e,
            // 'qrcode': 0xf134,
            // 'question-circle': 0x0128,
            // 'question': 0xf130,
            // 'quote-left': 0x010d,
            // 'quote-right': 0x010e,
            // 'random': 0xf131,
            // 'recycle': 0x01b8,
            // 'redo-alt': 0x001e,
            // 'redo': 0x02f9,
            // 'reply-all': 0x03e5,
            // 'reply': 0x0122,
            // 'retweet': 0xf132,
            // 'road': 0x0018,
            // 'rocket': 0x0135,
            // 'rss': 0x0143,
            // 'ruble-sign': 0x0158,
            // 'rupee-sign': 0x0156,
            // 'search-minus': 0x0002,
            // 'search-plus': 0x0010,
            // 'search': 0x000e,
            // 'server': 0x0233,
            // 'share-alt': 0x01e0,
            // 'share-square': 0x01e1,
            // 'share': 0x014d,
            // 'shekel-sign': 0x020b,
            // 'shield-alt': 0x03ed,
            // 'ship': 0x021a,
            // 'shower': 0x02cc,
            // 'sign-in-alt': 0x02f6,
            // 'sign-language': 0x02a7,
            // 'sign-out-alt': 0x02f5,
            // 'signal': 0x0012,
            // 'sitemap': 0x00e8,
            // 'sliders-h': 0x01de,
            // 'smile': 0x0118,
            // 'snowflake': 0x02dc,
            // 'sort-alpha-down': 0x00dc,
            // 'sort-alpha-up': 0x015d,
            // 'sort-amount-down': 0x015e,
            // 'sort-amount-up': 0x0160,
            // 'sort-down': 0x0161,
            // 'sort-numeric-down': 0x00dd,
            // 'sort-numeric-up': 0x0162,
            // 'sort-up': 0x0163,
            // 'sort': 0x00de,
            // 'spinner': 0x0110,
            // 'square-full': 0x00c8,
            // 'square': 0x045c,
            // 'star-half': 0x0005,
            // 'star': 0xf135,
            // 'step-backward': 0x0048,
            // 'step-forward': 0xf136,
            // 'stethoscope': 0x00f1,
            // 'sticky-note': 0x0249,
            // 'stop-circle': 0xf137,
            // 'stop': 0x028d,
            // 'stopwatch': 0x02f2,
            // 'street-view': 0x021d,
            // 'strikethrough': 0x00cc,
            // 'subscript': 0x012c,
            // 'subway': 0x0239,
            // 'suitcase': 0x00f2,
            // 'sun': 0x0185,
            // 'superscript': 0x012b,
            // 'sync-alt': 0xf140,
            // 'sync': 0x02f1,
            // 'table-tennis': 0x00ce,
            // 'table': 0x045d,
            // 'tablet-alt': 0x010a,
            // 'tablet': 0x03fa,
            // 'tachometer-alt': 0x03fd,
            // 'tag': 0xf138,
            // 'tags': 0x002c,
            // 'tasks': 0x00ae,
            // 'taxi': 0x01ba,
            // 'terminal': 0x0120,
            // 'text-height': 0xf145,
            // 'text-width': 0xf139,
            // 'th-large': 0xf13a,
            // 'th-list': 0xf13b,
            // 'th': 0x000b,
            // 'thermometer-empty': 0x02cb,
            // 'thermometer-full': 0x02c7,
            // 'thermometer-half': 0x02c9,
            // 'thermometer-quarter': 0x02ca,
            // 'thermometer-three-quarters': 0x02c8,
            // 'thumbs-down': 0x0165,
            // 'thumbs-up': 0x0164,
            // 'thumbtack': 0x008d,
            // 'ticket-alt': 0x03ff,
            // 'times-circle': 0xf13c,
            // 'times': 0x0057,
            // 'tint': 0xf141,
            // 'toggle-off': 0x0204,
            // 'toggle-on': 0x0205,
            // 'trademark': 0x025c,
            // 'train': 0x0238,
            // 'transgender-alt': 0x0224,
            // 'transgender': 0x0225,
            // 'trash-alt': 0x01f8,
            // 'trash': 0x02ed,
            // 'tree': 0x01bb,
            // 'trophy': 0xf13d,
            // 'truck': 0x00d1,
            // 'tty': 0x01e4,
            // 'tv': 0x026c,
            // 'umbrella': 0x00e9,
            // 'underline': 0x00cd,
            // 'undo-alt': 0x00e2,
            // 'undo': 0x02ea,
            // 'universal-access': 0x029a,
            // 'university': 0x019c,
            // 'unlink': 0x0127,
            // 'unlock-alt': 0x009c,
            // 'unlock': 0x013e,
            // 'upload': 0xf13e,
            // 'user-circle': 0x0007,
            // 'user-md': 0x02bd,
            // 'user-plus': 0x00f0,
            // 'user-secret': 0x0234,
            // 'user-times': 0x021b,
            // 'user': 0x0235,
            // 'users': 0x00c0,
            // 'utensil-spoon': 0x02e5,
            // 'utensils': 0x02e7,
            // 'venus-double': 0x0221,
            // 'venus-mars': 0x0226,
            // 'venus': 0x0228,
            // 'video': 0x003d,
            // 'volleyball-ball': 0x045f,
            // 'volume-down': 0xf142,
            // 'volume-off': 0xf143,
            // 'volume-up': 0xf144,
            // 'wheelchair': 0x0193,
            // 'wifi': 0x01eb,
            // 'window-close': 0x0410,
            // 'window-maximize': 0x02d0,
            // 'window-minimize': 0x02d1,
            // 'window-restore': 0x02d2,
            // 'won-sign': 0x0159,
            // 'wrench': 0xf13f,
            // 'yen-sign': 0x0157

            // FontAesome mappings direct from
            // https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/advanced-options/metadata/icons.yml
            '500px': 0x0f26e,
            'accessible-icon': 0x0f368,
            'accusoft': 0x0f369,
            'address-book': 0x0f2b9,
            'address-card': 0x0f2bb,
            'adjust': 0x0f042,
            'adn': 0x0f170,
            'adversal': 0x0f36a,
            'affiliatetheme': 0x0f36b,
            'algolia': 0x0f36c,
            'align-center': 0x0f037,
            'align-justify': 0x0f039,
            'align-left': 0x0f036,
            'align-right': 0x0f038,
            'allergies': 0x0f461,
            'amazon': 0x0f270,
            'amazon-pay': 0x0f42c,
            'ambulance': 0x0f0f9,
            'american-sign-language-interpreting': 0x0f2a3,
            'amilia': 0x0f36d,
            'anchor': 0x0f13d,
            'android': 0x0f17b,
            'angellist': 0x0f209,
            'angle-double-down': 0x0f103,
            'angle-double-left': 0x0f100,
            'angle-double-right': 0x0f101,
            'angle-double-up': 0x0f102,
            'angle-down': 0x0f107,
            'angle-left': 0x0f104,
            'angle-right': 0x0f105,
            'angle-up': 0x0f106,
            'angrycreative': 0x0f36e,
            'angular': 0x0f420,
            'app-store': 0x0f36f,
            'app-store-ios': 0x0f370,
            'apper': 0x0f371,
            'apple': 0x0f179,
            'apple-pay': 0x0f415,
            'archive': 0x0f187,
            'arrow-alt-circle-down': 0x0f358,
            'arrow-alt-circle-left': 0x0f359,
            'arrow-alt-circle-right': 0x0f35a,
            'arrow-alt-circle-up': 0x0f35b,
            'arrow-circle-down': 0x0f0ab,
            'arrow-circle-left': 0x0f0a8,
            'arrow-circle-right': 0x0f0a9,
            'arrow-circle-up': 0x0f0aa,
            'arrow-down': 0x0f063,
            'arrow-left': 0x0f060,
            'arrow-right': 0x0f061,
            'arrow-up': 0x0f062,
            'arrows-alt': 0x0f0b2,
            'arrows-alt-h': 0x0f337,
            'arrows-alt-v': 0x0f338,
            'assistive-listening-systems': 0x0f2a2,
            'asterisk': 0x0f069,
            'asymmetrik': 0x0f372,
            'at': 0x0f1fa,
            'audible': 0x0f373,
            'audio-description': 0x0f29e,
            'autoprefixer': 0x0f41c,
            'avianex': 0x0f374,
            'aviato': 0x0f421,
            'aws': 0x0f375,
            'backward': 0x0f04a,
            'balance-scale': 0x0f24e,
            'ban': 0x0f05e,
            'band-aid': 0x0f462,
            'bandcamp': 0x0f2d5,
            'barcode': 0x0f02a,
            'bars': 0x0f0c9,
            'baseball-ball': 0x0f433,
            'basketball-ball': 0x0f434,
            'bath': 0x0f2cd,
            'battery-empty': 0x0f244,
            'battery-full': 0x0f240,
            'battery-half': 0x0f242,
            'battery-quarter': 0x0f243,
            'battery-three-quarters': 0x0f241,
            'bed': 0x0f236,
            'beer': 0x0f0fc,
            'behance': 0x0f1b4,
            'behance-square': 0x0f1b5,
            'bell': 0x0f0f3,
            'bell-slash': 0x0f1f6,
            'bicycle': 0x0f206,
            'bimobject': 0x0f378,
            'binoculars': 0x0f1e5,
            'birthday-cake': 0x0f1fd,
            'bitbucket': 0x0f171,
            'bitcoin': 0x0f379,
            'bity': 0x0f37a,
            'black-tie': 0x0f27e,
            'blackberry': 0x0f37b,
            'blender': 0x0f517,
            'blind': 0x0f29d,
            'blogger': 0x0f37c,
            'blogger-b': 0x0f37d,
            'bluetooth': 0x0f293,
            'bluetooth-b': 0x0f294,
            'bold': 0x0f032,
            'bolt': 0x0f0e7,
            'bomb': 0x0f1e2,
            'book': 0x0f02d,
            'book-open': 0x0f518,
            'bookmark': 0x0f02e,
            'bowling-ball': 0x0f436,
            'box': 0x0f466,
            'box-open': 0x0f49e,
            'boxes': 0x0f468,
            'braille': 0x0f2a1,
            'briefcase': 0x0f0b1,
            'briefcase-medical': 0x0f469,
            'broadcast-tower': 0x0f519,
            'broom': 0x0f51a,
            'btc': 0x0f15a,
            'bug': 0x0f188,
            'building': 0x0f1ad,
            'bullhorn': 0x0f0a1,
            'bullseye': 0x0f140,
            'burn': 0x0f46a,
            'buromobelexperte': 0x0f37f,
            'bus': 0x0f207,
            'buysellads': 0x0f20d,
            'calculator': 0x0f1ec,
            'calendar': 0x0f133,
            'calendar-alt': 0x0f073,
            'calendar-check': 0x0f274,
            'calendar-minus': 0x0f272,
            'calendar-plus': 0x0f271,
            'calendar-times': 0x0f273,
            'camera': 0x0f030,
            'capsules': 0x0f46b,
            'car': 0x0f1b9,
            'caret-down': 0x0f0d7,
            'caret-left': 0x0f0d9,
            'caret-right': 0x0f0da,
            'caret-square-down': 0x0f150,
            'caret-square-left': 0x0f191,
            'caret-square-right': 0x0f152,
            'caret-square-up': 0x0f151,
            'caret-up': 0x0f0d8,
            'cart-arrow-down': 0x0f218,
            'cart-plus': 0x0f217,
            'cc-amazon-pay': 0x0f42d,
            'cc-amex': 0x0f1f3,
            'cc-apple-pay': 0x0f416,
            'cc-diners-club': 0x0f24c,
            'cc-discover': 0x0f1f2,
            'cc-jcb': 0x0f24b,
            'cc-mastercard': 0x0f1f1,
            'cc-paypal': 0x0f1f4,
            'cc-stripe': 0x0f1f5,
            'cc-visa': 0x0f1f0,
            'centercode': 0x0f380,
            'certificate': 0x0f0a3,
            'chalkboard': 0x0f51b,
            'chalkboard-teacher': 0x0f51c,
            'chart-area': 0x0f1fe,
            'chart-bar': 0x0f080,
            'chart-line': 0x0f201,
            'chart-pie': 0x0f200,
            'check': 0x0f00c,
            'check-circle': 0x0f058,
            'check-square': 0x0f14a,
            'chess': 0x0f439,
            'chess-bishop': 0x0f43a,
            'chess-board': 0x0f43c,
            'chess-king': 0x0f43f,
            'chess-knight': 0x0f441,
            'chess-pawn': 0x0f443,
            'chess-queen': 0x0f445,
            'chess-rook': 0x0f447,
            'chevron-circle-down': 0x0f13a,
            'chevron-circle-left': 0x0f137,
            'chevron-circle-right': 0x0f138,
            'chevron-circle-up': 0x0f139,
            'chevron-down': 0x0f078,
            'chevron-left': 0x0f053,
            'chevron-right': 0x0f054,
            'chevron-up': 0x0f077,
            'child': 0x0f1ae,
            'chrome': 0x0f268,
            'church': 0x0f51d,
            'circle': 0x0f111,
            'circle-notch': 0x0f1ce,
            'clipboard': 0x0f328,
            'clipboard-check': 0x0f46c,
            'clipboard-list': 0x0f46d,
            'clock': 0x0f017,
            'clone': 0x0f24d,
            'closed-captioning': 0x0f20a,
            'cloud': 0x0f0c2,
            'cloud-download-alt': 0x0f381,
            'cloud-upload-alt': 0x0f382,
            'cloudscale': 0x0f383,
            'cloudsmith': 0x0f384,
            'cloudversify': 0x0f385,
            'code': 0x0f121,
            'code-branch': 0x0f126,
            'codepen': 0x0f1cb,
            'codiepie': 0x0f284,
            'coffee': 0x0f0f4,
            'cog': 0x0f013,
            'cogs': 0x0f085,
            'coins': 0x0f51e,
            'columns': 0x0f0db,
            'comment': 0x0f075,
            'comment-alt': 0x0f27a,
            'comment-dots': 0x0f4ad,
            'comment-slash': 0x0f4b3,
            'comments': 0x0f086,
            'compact-disc': 0x0f51f,
            'compass': 0x0f14e,
            'compress': 0x0f066,
            'connectdevelop': 0x0f20e,
            'contao': 0x0f26d,
            'copy': 0x0f0c5,
            'copyright': 0x0f1f9,
            'couch': 0x0f4b8,
            'cpanel': 0x0f388,
            'creative-commons': 0x0f25e,
            'creative-commons-by': 0x0f4e7,
            'creative-commons-nc': 0x0f4e8,
            'creative-commons-nc-eu': 0x0f4e9,
            'creative-commons-nc-jp': 0x0f4ea,
            'creative-commons-nd': 0x0f4eb,
            'creative-commons-pd': 0x0f4ec,
            'creative-commons-pd-alt': 0x0f4ed,
            'creative-commons-remix': 0x0f4ee,
            'creative-commons-sa': 0x0f4ef,
            'creative-commons-sampling': 0x0f4f0,
            'creative-commons-sampling-plus': 0x0f4f1,
            'creative-commons-share': 0x0f4f2,
            'credit-card': 0x0f09d,
            'crop': 0x0f125,
            'crosshairs': 0x0f05b,
            'crow': 0x0f520,
            'crown': 0x0f521,
            'css3': 0x0f13c,
            'css3-alt': 0x0f38b,
            'cube': 0x0f1b2,
            'cubes': 0x0f1b3,
            'cut': 0x0f0c4,
            'cuttlefish': 0x0f38c,
            'd-and-d': 0x0f38d,
            'dashcube': 0x0f210,
            'database': 0x0f1c0,
            'deaf': 0x0f2a4,
            'delicious': 0x0f1a5,
            'deploydog': 0x0f38e,
            'deskpro': 0x0f38f,
            'desktop': 0x0f108,
            'deviantart': 0x0f1bd,
            'diagnoses': 0x0f470,
            'dice': 0x0f522,
            'dice-five': 0x0f523,
            'dice-four': 0x0f524,
            'dice-one': 0x0f525,
            'dice-six': 0x0f526,
            'dice-three': 0x0f527,
            'dice-two': 0x0f528,
            'digg': 0x0f1a6,
            'digital-ocean': 0x0f391,
            'discord': 0x0f392,
            'discourse': 0x0f393,
            'divide': 0x0f529,
            'dna': 0x0f471,
            'dochub': 0x0f394,
            'docker': 0x0f395,
            'dollar-sign': 0x0f155,
            'dolly': 0x0f472,
            'dolly-flatbed': 0x0f474,
            'donate': 0x0f4b9,
            'door-closed': 0x0f52a,
            'door-open': 0x0f52b,
            'dot-circle': 0x0f192,
            'dove': 0x0f4ba,
            'download': 0x0f019,
            'draft2digital': 0x0f396,
            'dribbble': 0x0f17d,
            'dribbble-square': 0x0f397,
            'dropbox': 0x0f16b,
            'drupal': 0x0f1a9,
            'dumbbell': 0x0f44b,
            'dyalog': 0x0f399,
            'earlybirds': 0x0f39a,
            'ebay': 0x0f4f4,
            'edge': 0x0f282,
            'edit': 0x0f044,
            'eject': 0x0f052,
            'elementor': 0x0f430,
            'ellipsis-h': 0x0f141,
            'ellipsis-v': 0x0f142,
            'ember': 0x0f423,
            'empire': 0x0f1d1,
            'envelope': 0x0f0e0,
            'envelope-open': 0x0f2b6,
            'envelope-square': 0x0f199,
            'envira': 0x0f299,
            'equals': 0x0f52c,
            'eraser': 0x0f12d,
            'erlang': 0x0f39d,
            'ethereum': 0x0f42e,
            'etsy': 0x0f2d7,
            'euro-sign': 0x0f153,
            'exchange-alt': 0x0f362,
            'exclamation': 0x0f12a,
            'exclamation-circle': 0x0f06a,
            'exclamation-triangle': 0x0f071,
            'expand': 0x0f065,
            'expand-arrows-alt': 0x0f31e,
            'expeditedssl': 0x0f23e,
            'external-link-alt': 0x0f35d,
            'external-link-square-alt': 0x0f360,
            'eye': 0x0f06e,
            'eye-dropper': 0x0f1fb,
            'eye-slash': 0x0f070,
            'facebook': 0x0f09a,
            'facebook-f': 0x0f39e,
            'facebook-messenger': 0x0f39f,
            'facebook-square': 0x0f082,
            'fast-backward': 0x0f049,
            'fast-forward': 0x0f050,
            'fax': 0x0f1ac,
            'feather': 0x0f52d,
            'female': 0x0f182,
            'fighter-jet': 0x0f0fb,
            // 'file': 0x0f15b,
            // 'file-alt': 0x0f15c,
            // 'file-archive': 0x0f1c6,
            // 'file-audio': 0x0f1c7,
            // 'file-code': 0x0f1c9,
            // 'file-excel': 0x0f1c3,
            // 'file-image': 0x0f1c5,
            // 'file-medical': 0x0f477,
            // 'file-medical-alt': 0x0f478,
            // 'file-pdf': 0x0f1c1,
            // 'file-powerpoint': 0x0f1c4,
            // 'file-video': 0x0f1c8,
            // 'file-word': 0x0f1c2,
            'file-signature': 0x0f573,
            'film': 0x0f008,
            'filter': 0x0f0b0,
            'fire': 0x0f06d,
            'fire-extinguisher': 0x0f134,
            'firefox': 0x0f269,
            'first-aid': 0x0f479,
            'first-order': 0x0f2b0,
            'first-order-alt': 0x0f50a,
            'firstdraft': 0x0f3a1,
            'flag': 0x0f024,
            'flag-checkered': 0x0f11e,
            'flask': 0x0f0c3,
            'flickr': 0x0f16e,
            'flipboard': 0x0f44d,
            'fly': 0x0f417,
            'folder': 0x0f07b,
            'folder-open': 0x0f07c,
            'font': 0x0f031,
            'font-awesome': 0x0f2b4,
            'font-awesome-alt': 0x0f35c,
            'font-awesome-flag': 0x0f425,
            'font-awesome-logo-full':0x0f4e6,
            'fonticons': 0x0f280,
            'fonticons-fi': 0x0f3a2,
            'football-ball': 0x0f44e,
            'fort-awesome': 0x0f286,
            'fort-awesome-alt': 0x0f3a3,
            'forumbee': 0x0f211,
            'forward': 0x0f04e,
            'foursquare': 0x0f180,
            'free-code-camp': 0x0f2c5,
            'freebsd': 0x0f3a4,
            'frog': 0x0f52e,
            // 'frown': 0x0f119,
            'fulcrum': 0x0f50b,
            'futbol': 0x0f1e3,
            'galactic-republic': 0x0f50c,
            'galactic-senate': 0x0f50d,
            'gamepad': 0x0f11b,
            'gas-pump': 0x0f52f,
            'gavel': 0x0f0e3,
            'gem': 0x0f3a5,
            'genderless': 0x0f22d,
            'get-pocket': 0x0f265,
            'gg': 0x0f260,
            'gg-circle': 0x0f261,
            'gift': 0x0f06b,
            'git': 0x0f1d3,
            'git-square': 0x0f1d2,
            'github': 0x0f09b,
            'github-alt': 0x0f113,
            'github-square': 0x0f092,
            'gitkraken': 0x0f3a6,
            'gitlab': 0x0f296,
            'gitter': 0x0f426,
            'glass-martini': 0x0f000,
            'glasses': 0x0f530,
            'glide': 0x0f2a5,
            'glide-g': 0x0f2a6,
            'globe': 0x0f0ac,
            'gofore': 0x0f3a7,
            'golf-ball': 0x0f450,
            'goodreads': 0x0f3a8,
            'goodreads-g': 0x0f3a9,
            'google': 0x0f1a0,
            'google-drive': 0x0f3aa,
            'google-play': 0x0f3ab,
            'google-plus': 0x0f2b3,
            'google-plus-g': 0x0f0d5,
            'google-plus-square': 0x0f0d4,
            'google-wallet': 0x0f1ee,
            'graduation-cap': 0x0f19d,
            'gratipay': 0x0f184,
            'grav': 0x0f2d6,
            'greater-than': 0x0f531,
            'greater-than-equal': 0x0f532,
            'gripfire': 0x0f3ac,
            'grunt': 0x0f3ad,
            'gulp': 0x0f3ae,
            'h-square': 0x0f0fd,
            'hacker-news': 0x0f1d4,
            'hacker-news-square': 0x0f3af,
            'hand-holding': 0x0f4bd,
            'hand-holding-heart': 0x0f4be,
            'hand-holding-usd': 0x0f4c0,
            'hand-lizard': 0x0f258,
            'hand-paper': 0x0f256,
            'hand-peace': 0x0f25b,
            'hand-point-down': 0x0f0a7,
            'hand-point-left': 0x0f0a5,
            'hand-point-right': 0x0f0a4,
            'hand-point-up': 0x0f0a6,
            'hand-pointer': 0x0f25a,
            'hand-rock': 0x0f255,
            'hand-scissors': 0x0f257,
            'hand-spock': 0x0f259,
            'hands': 0x0f4c2,
            'hands-helping': 0x0f4c4,
            'handshake': 0x0f2b5,
            'hashtag': 0x0f292,
            'hdd': 0x0f0a0,
            'heading': 0x0f1dc,
            'headphones': 0x0f025,
            'heart': 0x0f004,
            'heartbeat': 0x0f21e,
            'helicopter': 0x0f533,
            'hips': 0x0f452,
            'hire-a-helper': 0x0f3b0,
            'history': 0x0f1da,
            // 'hockey-puck': 0x0f453,
            'home': 0x0f015,
            'hooli': 0x0f427,
            'hospital': 0x0f0f8,
            'hospital-alt': 0x0f47d,
            'hospital-symbol': 0x0f47e,
            'hotjar': 0x0f3b1,
            'hourglass': 0x0f254,
            'hourglass-end': 0x0f253,
            'hourglass-half': 0x0f252,
            'hourglass-start': 0x0f251,
            'houzz': 0x0f27c,
            'html5': 0x0f13b,
            'hubspot': 0x0f3b2,
            'i-cursor': 0x0f246,
            'id-badge': 0x0f2c1,
            'id-card': 0x0f2c2,
            'id-card-alt': 0x0f47f,
            'image': 0x0f03e,
            'images': 0x0f302,
            'imdb': 0x0f2d8,
            'inbox': 0x0f01c,
            'indent': 0x0f03c,
            'industry': 0x0f275,
            'infinity': 0x0f534,
            'info': 0x0f129,
            'info-circle': 0x0f05a,
            'instagram': 0x0f16d,
            'internet-explorer': 0x0f26b,
            'ioxhost': 0x0f208,
            'italic': 0x0f033,
            'itunes': 0x0f3b4,
            'itunes-note': 0x0f3b5,
            'java': 0x0f4e4,
            'jedi-order': 0x0f50e,
            'jenkins': 0x0f3b6,
            'joget': 0x0f3b7,
            'joomla': 0x0f1aa,
            'js': 0x0f3b8,
            'js-square': 0x0f3b9,
            'jsfiddle': 0x0f1cc,
            'key': 0x0f084,
            'keybase': 0x0f4f5,
            'keyboard': 0x0f11c,
            'keycdn': 0x0f3ba,
            'kickstarter': 0x0f3bb,
            'kickstarter-k': 0x0f3bc,
            'kiwi-bird': 0x0f535,
            'korvue': 0x0f42f,
            'language': 0x0f1ab,
            'laptop': 0x0f109,
            'laravel': 0x0f3bd,
            'lastfm': 0x0f202,
            'lastfm-square': 0x0f203,
            'leaf': 0x0f06c,
            'leanpub': 0x0f212,
            'lemon': 0x0f094,
            'less': 0x0f41d,
            'less-than': 0x0f536,
            'less-than-equal': 0x0f537,
            'level-down-alt': 0x0f3be,
            'level-up-alt': 0x0f3bf,
            'life-ring': 0x0f1cd,
            'lightbulb': 0x0f0eb,
            'line': 0x0f3c0,
            'link': 0x0f0c1,
            'linkedin': 0x0f08c,
            'linkedin-in': 0x0f0e1,
            'linode': 0x0f2b8,
            'linux': 0x0f17c,
            'lira-sign': 0x0f195,
            'list': 0x0f03a,
            'list-alt': 0x0f022,
            'list-ol': 0x0f0cb,
            'list-ul': 0x0f0ca,
            'location-arrow': 0x0f124,
            'lock': 0x0f023,
            'lock-open': 0x0f3c1,
            'long-arrow-alt-down': 0x0f309,
            'long-arrow-alt-left': 0x0f30a,
            'long-arrow-alt-right': 0x0f30b,
            'long-arrow-alt-up': 0x0f30c,
            'low-vision': 0x0f2a8,
            'lyft': 0x0f3c3,
            'magento': 0x0f3c4,
            'magic': 0x0f0d0,
            'magnet': 0x0f076,
            'male': 0x0f183,
            'mandalorian': 0x0f50f,
            'map': 0x0f279,
            'map-marker': 0x0f041,
            'map-marker-alt': 0x0f3c5,
            'map-pin': 0x0f276,
            'map-signs': 0x0f277,
            'mars': 0x0f222,
            'mars-double': 0x0f227,
            'mars-stroke': 0x0f229,
            'mars-stroke-h': 0x0f22b,
            'mars-stroke-v': 0x0f22a,
            'mastodon': 0x0f4f6,
            'maxcdn': 0x0f136,
            'medapps': 0x0f3c6,
            'medium': 0x0f23a,
            'medium-m': 0x0f3c7,
            'medkit': 0x0f0fa,
            'medrt': 0x0f3c8,
            'meetup': 0x0f2e0,
            // 'meh': 0x0f11a,
            'memory': 0x0f538,
            'mercury': 0x0f223,
            'microchip': 0x0f2db,
            'microphone': 0x0f130,
            'microphone-alt': 0x0f3c9,
            'microphone-alt-slash': 0x0f539,
            'microphone-slash': 0x0f131,
            'microsoft': 0x0f3ca,
            'minus': 0x0f068,
            'minus-circle': 0x0f056,
            'minus-square': 0x0f146,
            'mix': 0x0f3cb,
            'mixcloud': 0x0f289,
            'mizuni': 0x0f3cc,
            'mobile': 0x0f10b,
            'mobile-alt': 0x0f3cd,
            'modx': 0x0f285,
            'monero': 0x0f3d0,
            'money-bill': 0x0f0d6,
            'money-bill-alt': 0x0f3d1,
            'money-bill-wave': 0x0f53a,
            'money-bill-wave-alt': 0x0f53b,
            'money-check': 0x0f53c,
            'money-check-alt': 0x0f53d,
            'moon': 0x0f186,
            'motorcycle': 0x0f21c,
            'mouse-pointer': 0x0f245,
            'music': 0x0f001,
            'napster': 0x0f3d2,
            'neuter': 0x0f22c,
            'newspaper': 0x0f1ea,
            'nintendo-switch': 0x0f418,
            'node': 0x0f419,
            'node-js': 0x0f3d3,
            'not-equal': 0x0f53e,
            'notes-medical': 0x0f481,
            'npm': 0x0f3d4,
            'ns8': 0x0f3d5,
            'nutritionix': 0x0f3d6,
            'object-group': 0x0f247,
            'object-ungroup': 0x0f248,
            'odnoklassniki': 0x0f263,
            'odnoklassniki-square': 0x0f264,
            'old-republic': 0x0f510,
            'opencart': 0x0f23d,
            'openid': 0x0f19b,
            'opera': 0x0f26a,
            'optin-monster': 0x0f23c,
            'osi': 0x0f41a,
            'outdent': 0x0f03b,
            'page4': 0x0f3d7,
            'pagelines': 0x0f18c,
            'paint-brush': 0x0f1fc,
            'palette': 0x0f53f,
            'palfed': 0x0f3d8,
            'pallet': 0x0f482,
            'paper-plane': 0x0f1d8,
            'paperclip': 0x0f0c6,
            'parachute-box': 0x0f4cd,
            'paragraph': 0x0f1dd,
            'parking': 0x0f540,
            'passport': 0x0f5ab,
            'paste': 0x0f0ea,
            'patreon': 0x0f3d9,
            'pause': 0x0f04c,
            'pause-circle': 0x0f28b,
            'paw': 0x0f1b0,
            'paypal': 0x0f1ed,
            'pen-square': 0x0f14b,
            'pencil-alt': 0x0f303,
            'people-carry': 0x0f4ce,
            'percent': 0x0f295,
            'percentage': 0x0f541,
            'periscope': 0x0f3da,
            'phabricator': 0x0f3db,
            'phoenix-framework': 0x0f3dc,
            'phoenix-squadron': 0x0f511,
            'phone': 0x0f095,
            'phone-slash': 0x0f3dd,
            'phone-square': 0x0f098,
            'phone-volume': 0x0f2a0,
            'php': 0x0f457,
            'pied-piper': 0x0f2ae,
            'pied-piper-alt': 0x0f1a8,
            'pied-piper-hat': 0x0f4e5,
            'pied-piper-pp': 0x0f1a7,
            'piggy-bank': 0x0f4d3,
            'pills': 0x0f484,
            'pinterest': 0x0f0d2,
            'pinterest-p': 0x0f231,
            'pinterest-square': 0x0f0d3,
            'plane': 0x0f072,
            'play': 0x0f04b,
            'play-circle': 0x0f144,
            'playstation': 0x0f3df,
            'plug': 0x0f1e6,
            'plus': 0x0f067,
            'plus-circle': 0x0f055,
            'plus-square': 0x0f0fe,
            'podcast': 0x0f2ce,
            'poo': 0x0f2fe,
            'portrait': 0x0f3e0,
            'pound-sign': 0x0f154,
            'power-off': 0x0f011,
            'prescription-bottle': 0x0f485,
            'prescription-bottle-alt': 0x0f486,
            'print': 0x0f02f,
            'procedures': 0x0f487,
            'product-hunt': 0x0f288,
            'project-diagram': 0x0f542,
            'pushed': 0x0f3e1,
            'puzzle-piece': 0x0f12e,
            'python': 0x0f3e2,
            'qq': 0x0f1d6,
            'qrcode': 0x0f029,
            'question': 0x0f128,
            'question-circle': 0x0f059,
            'quidditch': 0x0f458,
            'quinscape': 0x0f459,
            'quora': 0x0f2c4,
            'quote-left': 0x0f10d,
            'quote-right': 0x0f10e,
            'r-project': 0x0f4f7,
            'random': 0x0f074,
            'ravelry': 0x0f2d9,
            'react': 0x0f41b,
            'readme': 0x0f4d5,
            'rebel': 0x0f1d0,
            'receipt': 0x0f543,
            'recycle': 0x0f1b8,
            'red-river': 0x0f3e3,
            'reddit': 0x0f1a1,
            'reddit-alien': 0x0f281,
            'reddit-square': 0x0f1a2,
            'redo': 0x0f01e,
            'redo-alt': 0x0f2f9,
            'registered': 0x0f25d,
            'rendact': 0x0f3e4,
            'renren': 0x0f18b,
            'reply': 0x0f3e5,
            'reply-all': 0x0f122,
            'replyd': 0x0f3e6,
            'researchgate': 0x0f4f8,
            'resolving': 0x0f3e7,
            'retweet': 0x0f079,
            'ribbon': 0x0f4d6,
            'road': 0x0f018,
            'robot': 0x0f544,
            'rocket': 0x0f135,
            'rocketchat': 0x0f3e8,
            'rockrms': 0x0f3e9,
            'rss': 0x0f09e,
            'rss-square': 0x0f143,
            'ruble-sign': 0x0f158,
            'ruler': 0x0f545,
            'ruler-combined': 0x0f546,
            'ruler-horizontal': 0x0f547,
            'ruler-vertical': 0x0f548,
            'rupee-sign': 0x0f156,
            'safari': 0x0f267,
            'sass': 0x0f41e,
            'save': 0x0f0c7,
            'schlix': 0x0f3ea,
            'school': 0x0f549,
            'screwdriver': 0x0f54a,
            'scribd': 0x0f28a,
            'search': 0x0f002,
            'search-minus': 0x0f010,
            'search-plus': 0x0f00e,
            'searchengin': 0x0f3eb,
            'seedling': 0x0f4d8,
            'sellcast': 0x0f2da,
            'sellsy': 0x0f213,
            'server': 0x0f233,
            'servicestack': 0x0f3ec,
            'share': 0x0f064,
            'share-alt': 0x0f1e0,
            'share-alt-square': 0x0f1e1,
            'share-square': 0x0f14d,
            'shekel-sign': 0x0f20b,
            'shield-alt': 0x0f3ed,
            'ship': 0x0f21a,
            'shipping-fast': 0x0f48b,
            'shirtsinbulk': 0x0f214,
            'shoe-prints': 0x0f54b,
            'shopping-bag': 0x0f290,
            'shopping-basket': 0x0f291,
            'shopping-cart': 0x0f07a,
            'shower': 0x0f2cc,
            'sign': 0x0f4d9,
            'sign-in-alt': 0x0f2f6,
            'sign-language': 0x0f2a7,
            'sign-out-alt': 0x0f2f5,
            'signal': 0x0f012,
            'simplybuilt': 0x0f215,
            'sistrix': 0x0f3ee,
            'sitemap': 0x0f0e8,
            'sith': 0x0f512,
            'skull': 0x0f54c,
            'skyatlas': 0x0f216,
            'skype': 0x0f17e,
            'slack': 0x0f198,
            'slack-hash': 0x0f3ef,
            'sliders-h': 0x0f1de,
            'slideshare': 0x0f1e7,
            // 'smile': 0x0f118,
            'smoking': 0x0f48d,
            'smoking-ban': 0x0f54d,
            'snapchat': 0x0f2ab,
            'snapchat-ghost': 0x0f2ac,
            'snapchat-square': 0x0f2ad,
            'snowflake': 0x0f2dc,
            'sort': 0x0f0dc,
            'sort-alpha-down': 0x0f15d,
            'sort-alpha-up': 0x0f15e,
            'sort-amount-down': 0x0f160,
            'sort-amount-up': 0x0f161,
            'sort-down': 0x0f0dd,
            'sort-numeric-down': 0x0f162,
            'sort-numeric-up': 0x0f163,
            'sort-up': 0x0f0de,
            'soundcloud': 0x0f1be,
            'space-shuttle': 0x0f197,
            'speakap': 0x0f3f3,
            'spinner': 0x0f110,
            'spotify': 0x0f1bc,
            'square': 0x0f0c8,
            'square-full': 0x0f45c,
            'stack-exchange': 0x0f18d,
            'stack-overflow': 0x0f16c,
            'star': 0x0f005,
            'star-half': 0x0f089,
            'staylinked': 0x0f3f5,
            'steam': 0x0f1b6,
            'steam-square': 0x0f1b7,
            'steam-symbol': 0x0f3f6,
            'step-backward': 0x0f048,
            'step-forward': 0x0f051,
            'stethoscope': 0x0f0f1,
            'sticker-mule': 0x0f3f7,
            'sticky-note': 0x0f249,
            'stop': 0x0f04d,
            'stop-circle': 0x0f28d,
            'stopwatch': 0x0f2f2,
            'store': 0x0f54e,
            'store-alt': 0x0f54f,
            'strava': 0x0f428,
            'stream': 0x0f550,
            'street-view': 0x0f21d,
            'strikethrough': 0x0f0cc,
            'stripe': 0x0f429,
            'stripe-s': 0x0f42a,
            'stroopwafel': 0x0f551,
            'studiovinari': 0x0f3f8,
            'stumbleupon': 0x0f1a4,
            'stumbleupon-circle': 0x0f1a3,
            'subscript': 0x0f12c,
            'subway': 0x0f239,
            'suitcase': 0x0f0f2,
            'sun': 0x0f185,
            'superpowers': 0x0f2dd,
            'superscript': 0x0f12b,
            'supple': 0x0f3f9,
            'sync': 0x0f021,
            'sync-alt': 0x0f2f1,
            'syringe': 0x0f48e,
            'table': 0x0f0ce,
            'table-tennis': 0x0f45d,
            'tablet': 0x0f10a,
            'tablet-alt': 0x0f3fa,
            'tablets': 0x0f490,
            'tachometer-alt': 0x0f3fd,
            'tag': 0x0f02b,
            'tags': 0x0f02c,
            'tape': 0x0f4db,
            'tasks': 0x0f0ae,
            'taxi': 0x0f1ba,
            'teamspeak': 0x0f4f9,
            'telegram': 0x0f2c6,
            'telegram-plane': 0x0f3fe,
            'tencent-weibo': 0x0f1d5,
            'terminal': 0x0f120,
            'text-height': 0x0f034,
            'text-width': 0x0f035,
            'th': 0x0f00a,
            'th-large': 0x0f009,
            'th-list': 0x0f00b,
            'themeisle': 0x0f2b2,
            'thermometer': 0x0f491,
            'thermometer-empty': 0x0f2cb,
            'thermometer-full': 0x0f2c7,
            'thermometer-half': 0x0f2c9,
            'thermometer-quarter': 0x0f2ca,
            'thermometer-three-quarters': 0x0f2c8,
            'thumbs-down': 0x0f165,
            'thumbs-up': 0x0f164,
            'thumbtack': 0x0f08d,
            'ticket-alt': 0x0f3ff,
            'times': 0x0f00d,
            'times-circle': 0x0f057,
            'tint': 0x0f043,
            'toggle-off': 0x0f204,
            'toggle-on': 0x0f205,
            //'toolbox': 0x0f552,
            'trade-federation': 0x0f513,
            'trademark': 0x0f25c,
            'train': 0x0f238,
            'transgender': 0x0f224,
            'transgender-alt': 0x0f225,
            'trash': 0x0f1f8,
            'trash-alt': 0x0f2ed,
            'tree': 0x0f1bb,
            'trello': 0x0f181,
            'tripadvisor': 0x0f262,
            'trophy': 0x0f091,
            'truck': 0x0f0d1,
            'truck-loading': 0x0f4de,
            'truck-moving': 0x0f4df,
            'tshirt': 0x0f553,
            'tty': 0x0f1e4,
            'tumblr': 0x0f173,
            'tumblr-square': 0x0f174,
            'tv': 0x0f26c,
            'twitch': 0x0f1e8,
            'twitter': 0x0f099,
            'twitter-square': 0x0f081,
            'typo3': 0x0f42b,
            'uber': 0x0f402,
            'uikit': 0x0f403,
            'umbrella': 0x0f0e9,
            'underline': 0x0f0cd,
            'undo': 0x0f0e2,
            'undo-alt': 0x0f2ea,
            'uniregistry': 0x0f404,
            'universal-access': 0x0f29a,
            'university': 0x0f19c,
            'unlink': 0x0f127,
            'unlock': 0x0f09c,
            'unlock-alt': 0x0f13e,
            'untappd': 0x0f405,
            'upload': 0x0f093,
            'usb': 0x0f287,
            'user': 0x0f007,
            'user-circle': 0x0f2bd,
            'user-md': 0x0f0f0,
            'user-minus': 0x0f503,
            'user-plus': 0x0f234,
            'user-secret': 0x0f21b,
            'user-times': 0x0f235,
            'users': 0x0f0c0,
            'users-cog': 0x0f509,
            'ussunnah': 0x0f407,
            'utensil-spoon': 0x0f2e5,
            'utensils': 0x0f2e7,
            'vaadin': 0x0f408,
            'venus': 0x0f221,
            'venus-double': 0x0f226,
            'venus-mars': 0x0f228,
            'viacoin': 0x0f237,
            'viadeo': 0x0f2a9,
            'viadeo-square': 0x0f2aa,
            'vial': 0x0f492,
            'vials': 0x0f493,
            'viber': 0x0f409,
            'video': 0x0f03d,
            'video-slash': 0x0f4e2,
            'vimeo': 0x0f40a,
            'vimeo-square': 0x0f194,
            'vimeo-v': 0x0f27d,
            'vine': 0x0f1ca,
            'vk': 0x0f189,
            'vnv': 0x0f40b,
            'volleyball-ball': 0x0f45f,
            'volume-down': 0x0f027,
            'volume-off': 0x0f026,
            'volume-up': 0x0f028,
            //'vuejs': 0x0f41f,
            //'walking': 0x0f554,
            'wallet': 0x0f555,
            'warehouse': 0x0f494,
            'weibo': 0x0f18a,
            'weight': 0x0f496,
            'weixin': 0x0f1d7,
            'whatsapp': 0x0f232,
            'whatsapp-square': 0x0f40c,
            'wheelchair': 0x0f193,
            'whmcs': 0x0f40d,
            'wifi': 0x0f1eb,
            'wikipedia-w': 0x0f266,
            'window-close': 0x0f410,
            'window-maximize': 0x0f2d0,
            'window-minimize': 0x0f2d1,
            'window-restore': 0x0f2d2,
            'windows': 0x0f17a,
            'wine-glass': 0x0f4e3,
            'wolf-pack-battalion': 0x0f514,
            'won-sign': 0x0f159,
            'wordpress': 0x0f19a,
            'wordpress-simple': 0x0f411,
            'wpbeginner': 0x0f297,
            'wpexplorer': 0x0f2de,
            'wpforms': 0x0f298,
            'wrench': 0x0f0ad,
            'x-ray': 0x0f497,
            // 'xbox': 0x0f412,
            'xing': 0x0f168,
            'xing-square': 0x0f169,
            'y-combinator': 0x0f23b,
            'yahoo': 0x0f19e,
            'yandex': 0x0f413,
            'yandex-international': 0x0f414,
            // 'yelp': 0x0f1e9,
            'yen-sign': 0x0f157,
            'yoast': 0x0f2b1,
            'youtube': 0x0f167,
            // 'youtube-square': 0x0f431
            // EBI-FUNCTIONAL
            // - Some duplicate icons have been removed
            // - In general key codes HAVE NOT changed
            // 'add': 0x002b,
            'add-job': 0x0029,
            // 'add-user': 0x0037,
            'align': 0x0069,
            'analyse': 0x0041,
            'analyse-percent_0': 0x0042,
            'analyse-percent_40': 0x0043,
            'analyse-percent_100': 0x0045,
            'analyse-graph': 0x007a,
            // 'approve': 0x002f,
            'approved-job': 0x0028,
            'attach': 0x0061,
            'browse': 0x0062,
            'close': 0x0078,
            'collapse': 0x0077,
            'collapse-closed': 0x0039,
            'collapse-open': 0x0038,
            'compare': 0x004f,
            'database-submit': 0x0044,
            // 'delete': 0x0064,
            'down-page': 0x2b07,
            'download-alt': 0x003d,
            'edit-user': 0x0035,
            'expand': 0x0075,
            'filter': 0x0066,
            'first-page': 0x005b,
            'fullscreen': 0x0046,
            'fullscreen-collapse': 0x0047,
            'hierarchy': 0x0068,
            'last-page': 0x005d,
            'lock': 0x004c,
            'login': 0x006c,
            'mapping': 0x0030,
            // 'menu': 0x004d,
            'move': 0x006d,
            'next-page': 0x003e,
            'play': 0x0076,
            'previous-page': 0x003c,
            'print': 0x0050,
            'redo': 0x007d,
            // 'refresh': 0x0052,
            'remove': 0x002d,
            // 'remove-user': 0x0036,
            'save': 0x0053,
            'scaleable': 0x0059,
            'search-document': 0x006a,
            'send': 0x006e,
            // 'settings': 0x0073,
            // 'stop': 0x006f,
            'submit': 0x005f,
            'tool': 0x0074,
            'unassigned-job': 0x002a,
            'up-page': 0x2b06,
            // 'view': 0x0034,
            // 'zoom-in': 0x0033,
            // 'zoom-out': 0x0032,
            // EBI-GENERIC
            // - Some duplicate icons have been removed
            // - Key codes have changed from old EBI-Generic
            'accommodation': 0xf220,
            // 'alert': 0xf22e,
            'alumni': 0xf22f,
            'announcement': 0xf230,
            'basket': 0xf23f,
            'beta': 0xf24a,
            'bike': 0xf24f,
            'biotech': 0xf250,
            'bus': 0xf207,
            'car': 0xf1b9,
            'careers': 0xf25f,
            'classification': 0xf26f,
            'contact': 0xf278,
            'crosslink': 0xf27b,
            'database': 0xf1c0,
            'discuss': 0xf27f,
            'documentation': 0xf283,
            'drug': 0xf28c,
            'elixir': 0xf28e,
            // 'email': 0xf28f,
            'embl': 0xf29b,
            'external-systems': 0xf29f,
            'face-to-face': 0xf2af,
            // 'find-us': 0xf2b7,
            'funding': 0xf2ba,
            'group': 0xf2be,
            'gtls': 0xf2bf,
            'health': 0xf2c0,
            'help': 0xf2c3,
            'info': 0xf129,
            'location': 0xf2cf,
            // 'lovedata': 0xf2d3,
            'mailing-list': 0xf2d4,
            'math': 0xf2df,
            'meet-us': 0xf2e1,
            'new': 0xf2e4,
            'newcomers': 0xf2e4,
            'nutraceuticals': 0xf2e8,
            'open-day': 0xf2e9,
            'publication': 0xf2ec,
            'research': 0xf2ee,
            'resource': 0xf2ef,
            'reviewed-data': 0xf2f0,
            'services': 0xf2f3,
            'steps': 0xf2f4,
            'support': 0xf2f7,
            'systems': 0xf2f8,
            'terms': 0xf2fa,
            'test': 0xf2fb,
            'text-mining': 0xf2fc,
            'toolkit': 0xf2fd,
            'train': 0xf238,
            'training': 0xf2ff,
            'tutorial': 0xf300,
            'unreviewed-data': 0xf301,
            'video': 0xf03d,
            'walk': 0xf304
          }
        }
      },

    },

    // 3. Copy the source SVGs into the font folders
    copy: {
      main: {
        files: [
          // includes files within path
          {expand: true, cwd: 'source/chemistry/', src: ['**'], dest: 'EBI-Chemistry/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/conceptual/', src: ['**'], dest: 'EBI-Conceptual/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/fileformats/', src: ['**'], dest: 'EBI-FileFormats/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/functional/', src: ['**'], dest: 'EBI-Functional/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/generic/', src: ['**'], dest: 'EBI-Generic/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/social/', src: ['**'], dest: 'EBI-SocialMedia/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }},
          {expand: true, cwd: 'source/species/', src: ['**'], dest: 'EBI-Species/static/svg', rename: function(dest, src) {
            return dest + '/' + src.replace('(','').replace(')','');
          }}
        ],
      },
    },
    // 4. Make the PNGs
    //    (and compiled CSS files for poteintal future use)
    grunticon: {
      chemistry: {
          files: [{
              expand: true,
              cwd: 'EBI-Chemistry/static/svg',
              src: ['*.svg'],
              dest: "EBI-Chemistry/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      conceptual: {
          files: [{
              expand: true,
              cwd: 'EBI-Conceptual/static/svg',
              src: ['*.svg'],
              dest: "EBI-Conceptual/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      fileformats: {
          files: [{
              expand: true,
              cwd: 'EBI-FileFormats/static/svg',
              src: ['*.svg'],
              dest: "EBI-FileFormats/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      functional: {
          files: [{
              expand: true,
              cwd: 'EBI-Functional/static/svg',
              src: ['*.svg'],
              dest: 'EBI-Functional/static'
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      generic: {
          files: [{
              expand: true,
              cwd: 'EBI-Generic/static/svg',
              src: ['*.svg'],
              dest: 'EBI-Generic/static'
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      social: {
          files: [{
              expand: true,
              cwd: 'EBI-SocialMedia/static/svg',
              src: ['*.svg'],
              dest: "EBI-SocialMedia/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
      species: {
          files: [{
              expand: true,
              cwd: 'EBI-Species/static/svg',
              src: ['*.svg'],
              dest: "EBI-Species/static"
          }],
          options: {
            // enhanceSVG: true,
            "previewTemplate": "templates/preview.hbs",
            // "template":        "templates/css.hbs",
            colors: {
              "white": "#ffffff"
            }
          }
      },
    },
    // 5. Combine the built webfont previews into a global template
    includes: {
      files: {
        debug: true,
        src: [
          'templates/partial.html',
          'templates/fonts.css'
        ],
        dest: '.', // Destination directory
        flatten: true,
        cwd: '.',
        options: {
          // silent: true,
          // banner: '<!-- To be consumed by the EBI Style Lab -->',
          includePath: [
            'EBI-Chemistry/fonts/',
            'EBI-Conceptual/fonts/',
            'EBI-Common/fonts/',
            'EBI-FileFormats/fonts/',
            'EBI-Functional/fonts/',
            'EBI-Generic/fonts/',
            'EBI-SocialMedia/fonts/',
            'EBI-Species/fonts/'
          ],

        }
      }
    }

    // grunticon: {
    //     all: {
    //         files: [{
    //             expand: true,
    //             cwd: 'icons/source',
    //             src: ['*.svg', '*.png'],
    //             dest: "icons/output"
    //         }],
    //         options: {
    //           // enhanceSVG: true,
    //           "previewTemplate": "templates/preview.hbs",
    //           "template":        "templates/css.hbs",
    //           colors: {
    //             "white": "#ffffff"
    //           },
    //           customselectors: {
    //             "species-ferret": [".icon.icon-species[data-icon=\"!\"]"],
    //             "species-bee": [".icon.icon-species[data-icon=\"$\"]"],
    //             "species-brachypodium": [".icon.icon-species[data-icon=\"%\"]"],
    //             "species-tick": [".icon.icon-species[data-icon=\"&\"]"],
    //             "species-bat": [".icon.icon-species[data-icon=\"(\"]"],
    //             "species-tomatoes": [".icon.icon-species[data-icon=\")\"]"],
    //             "species-orangutan": [".icon.icon-species[data-icon=\"*\"]"],
    //             "species-amoeba": [".icon.icon-species[data-icon=\"0\"]"],
    //             "species-mosquito": [".icon.icon-species[data-icon=\"1\"]"],
    //             "species-diatom": [".icon.icon-species[data-icon=\"2\"]"],
    //             "species-kangaroo-rat": [".icon.icon-species[data-icon=\"3\"]"],
    //             "species-louse": [".icon.icon-species[data-icon=\"4\"]"],
    //             "species-barley": [".icon.icon-species[data-icon=\"5\"]"],
    //             "species-rice": [".icon.icon-species[data-icon=\"6\"]"],
    //             "species-anolis": [".icon.icon-species[data-icon=\"7\"]"],
    //             "species-papio": [".icon.icon-species[data-icon=\"8\"]"],
    //             "species-monodelphis": [".icon.icon-species[data-icon=\"9\"]"],
    //             "species-plasmodium": [".icon.icon-species[data-icon=\"@\"]"],
    //             "species-cat": [".icon.icon-species[data-icon=\"A\"]"],
    //             "species-brassica": [".icon.icon-species[data-icon=\"B\"]"],
    //             "species-cow": [".icon.icon-species[data-icon=\"C\"]"],
    //             "species-dolphin": [".icon.icon-species[data-icon=\"D\"]"],
    //             "species-pufferfish": [".icon.icon-species[data-icon=\"E\"]"],
    //             "species-fly": [".icon.icon-species[data-icon=\"F\"]"],
    //             "species-gorilla": [".icon.icon-species[data-icon=\"G\"]"],
    //             "species-human": [".icon.icon-species[data-icon=\"H\"]"],
    //             "species-squirrel": [".icon.icon-species[data-icon=\"I\"]"],
    //             "species-ecoli": [".icon.icon-species[data-icon=\"L\"]"],
    //             "species-mouse": [".icon.icon-species[data-icon=\"M\"]"],
    //             "species-mouse-lemur": [".icon.icon-species[data-icon=\"N\"]"],
    //             "species-grapes": [".icon.icon-species[data-icon=\"0\"]"],
    //             "species-plant": [".icon.icon-species[data-icon=\"P\"]"],
    //             "species-shrew": [".icon.icon-species[data-icon=\"Q\"]"],
    //             "species-rat": [".icon.icon-species[data-icon=\"R\"]"],
    //             "species-spider": [".icon.icon-species[data-icon=\"S\"]"],
    //             "species-platypus": [".icon.icon-species[data-icon=\"U\"]"],
    //             "species-c-elegans": [".icon.icon-species[data-icon=\"W\"]"],
    //             "species-yeast": [".icon.icon-species[data-icon=\"Y\"]"],
    //             "species-zebrafish": [".icon.icon-species[data-icon=\"Z\"]"],
    //             "species-glycinemax": [".icon.icon-species[data-icon=\"^\"]"],
    //             "species-alpaca": [".icon.icon-species[data-icon=\"a\"]"],
    //             "species-bug": [".icon.icon-species[data-icon=\"b\"]"],
    //             "species-corn": [".icon.icon-species[data-icon=\"d\"]"],
    //             "species-dog": [".icon.icon-species[data-icon=\"d\"]"],
    //             "species-elephant": [".icon.icon-species[data-icon=\"e\"]"],
    //             "species-frog": [".icon.icon-species[data-icon=\"f\"]"],
    //             "species-guinea-pig": [".icon.icon-species[data-icon=\"g\"]"],
    //             "species-horse": [".icon.icon-species[data-icon=\"h\"]"],
    //             "species-chimpanzee": [".icon.icon-species[data-icon=\"i\"]"],
    //             "species-chicken": [".icon.icon-species[data-icon=\"k\"]"],
    //             "species-armadillo": [".icon.icon-species[data-icon=\"l\"]"],
    //             "species-finch": [".icon.icon-species[data-icon=\"n\"]"],
    //             "species-hedgehog": [".icon.icon-species[data-icon=\"o\"]"],
    //             "species-pig": [".icon.icon-species[data-icon=\"p\"]"],
    //             "species-monkey": [".icon.icon-species[data-icon=\"r\"]"],
    //             "species-scorpion": [".icon.icon-species[data-icon=\"s\"]"],
    //             "species-rabbit": [".icon.icon-species[data-icon=\"t\"]"],
    //             "species-fungus": [".icon.icon-species[data-icon=\"u\"]"],
    //             "species-virus": [".icon.icon-species[data-icon=\"v\"]"],
    //             "species-wallaby": [".icon.icon-species[data-icon=\"w\"]"],
    //             "species-sheep": [".icon.icon-species[data-icon=\"x\"]"],
    //             "species-aspergillus": [".icon.icon-species[data-icon=\"£\"]"],
    //             "*": [".icon[data-icon=\"$1\"]", ".icon.icon-$1"]
    //           }
    //         }
    //     }
    // }
  });
  grunt.registerTask('default', ['svgmin','webfont','grunticon','copy','includes']);

};
